/**
 * Experiment T11, step 2b - ask Chromium the metrics the renderer will have.
 *
 * ```
 * node tools/ground-truth/text/wordart-columns/measure-in-browser.ts <work-dir>
 * ```
 *
 * PowerPoint's answer is the reference; this is what ships. A WordArt column is
 * fitted against the font box rather than the em, and the font box a browser
 * reports is the only one the renderer can read - so the fit has to be scored
 * against this, not against a table lifted out of the font file.
 *
 * The same `OffscreenCanvas` the Worker measures on, not a DOM `<canvas>`.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { chromium } from 'playwright';

import { BAR, CJK, FACES, LATIN, MIXED, OVERLONG, UPRIGHT_LATIN } from './probes.ts';

/*
 * `page.evaluate` runs in Chromium and `tools/` is compiled with no DOM library,
 * so the surface this file uses is declared rather than imported - narrow enough
 * that a body which reaches for anything else fails to compile.
 */
interface BrowserMetrics {
  readonly width: number;
  readonly fontBoundingBoxAscent: number;
  readonly fontBoundingBoxDescent: number;
  readonly ideographicBaseline: number;
}
interface BrowserCtx {
  font: string;
  letterSpacing: string;
  fontKerning: string;
  measureText(text: string): BrowserMetrics;
}
interface BrowserCanvas {
  getContext(id: '2d'): BrowserCtx | null;
}

const arg = process.argv[2];
if (arg === undefined) throw new Error('usage: measure-in-browser.ts <work-dir>');
const work: string = arg;

/** The size the face box is read at, matching `FACE_BOX_PX` in the package. */
const AT_PX = 1000;

const browser = await chromium.launch();
try {
  const page = await browser.newPage();
  const faces = await page.evaluate(
    ({
      names,
      at,
      strings,
    }: {
      names: readonly string[];
      at: number;
      strings: readonly string[];
    }) => {
      const make = (
        globalThis as unknown as { OffscreenCanvas: new (w: number, h: number) => BrowserCanvas }
      ).OffscreenCanvas;
      const ctx = new make(1, 1).getContext('2d');
      if (ctx === null) throw new Error('no 2d context');
      return names.map((name) => {
        ctx.font = `${String(at)}px "${name}"`;
        ctx.letterSpacing = '0px';
        ctx.fontKerning = 'normal';
        const box = ctx.measureText('Hxg');
        const advances: Record<string, number> = {};
        for (const text of strings) {
          for (const glyph of [...text]) {
            advances[glyph] = ctx.measureText(glyph).width / at;
          }
        }
        return {
          face: name,
          ascent: box.fontBoundingBoxAscent / at,
          descent: box.fontBoundingBoxDescent / at,
          ideographic: -ctx.measureText('一').ideographicBaseline / at,
          advances,
        };
      });
    },
    { names: FACES, at: AT_PX, strings: [LATIN, CJK, MIXED, OVERLONG, BAR, UPRIGHT_LATIN] },
  );

  const userAgent = await page.evaluate(() => navigator.userAgent);
  writeFileSync(
    join(work, 'column-browser.json'),
    `${JSON.stringify(
      {
        $comment: 'GENERATED by tools/ground-truth/text/wordart-columns/measure-in-browser.ts',
        atPx: AT_PX,
        userAgent,
        faces,
      },
      null,
      2,
    )}\n`,
  );
  process.stdout.write(`column-browser.json: ${String(faces.length)} face(s)\n`);
  for (const face of faces) {
    const box = face.ascent + face.descent;
    process.stdout.write(
      `  ${face.face.padEnd(18)} font box ${box.toFixed(4)} em  ` +
        `so a column at 7/6 of it would be ${((box * 7) / 6).toFixed(4)}\n`,
    );
  }
} finally {
  await browser.close();
}
