/**
 * Windows' own date patterns, per locale and per `a:fld/@type`.
 *
 * **Generated. Do not edit.** Regenerate with
 * `node tools/ground-truth/text/bullets/write-tables.ts` after re-running experiment
 * T5; `fields.test.ts` re-derives every cell from
 * `corpus/ground-truth/bullets.json` and fails if the two disagree.
 *
 * 172 cells across 14 locales, derived from what PowerPoint
 * rendered and verified by re-rendering each pattern and comparing it to the
 * string it came from. 118 of the measured readings could not be turned into
 * a pattern at all - the Japanese era calendar among them - and are deliberately
 * absent rather than approximated: `renderField` shows the cached text for a
 * cell that is not here, which is a visibly stale date rather than a confidently
 * wrong one.
 */
export const FIELD_DATE_PATTERNS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  'ar-SA': {
    datetime12: 'dd/MM/yyyy hh:mm tt',
  },
  'de-DE': {
    datetime: 'dd.MM.yyyy',
    datetime1: 'dd.MM.yyyy',
    datetime10: 'HH:mm',
    datetime11: 'HH:mm:ss',
    datetime12: 'h:mm ',
    datetime13: 'h:mm:ss ',
    datetime2: 'dddd, d. MMMM yyyy',
    datetime3: 'dd/MM/yy',
    datetime4: 'd. MMMM yyyy',
    datetime5: 'yy-MM-dd',
    datetime6: 'MMMM yy',
    datetime8: 'dd.MM.yyyy HH:mm',
    datetime9: 'dd.MM.yyyy HH:mm:ss',
    datetimeFigureOut: 'dd.MM.yyyy',
    uaqdatetime1: 'dd.MM.yyyy',
    uaqdatetime2: 'dddd, d. MMMM yyyy',
  },
  'en-GB': {
    datetime: 'dd/MM/yyyy',
    datetime1: 'dd/MM/yyyy',
    datetime10: 'HH:mm',
    datetime11: 'HH:mm:ss',
    datetime2: 'dddd, dd MMMM yyyy',
    datetime3: 'd MMMM, yyyy',
    datetime4: 'dd MMMM yyyy',
    datetime6: 'MMMM yy',
    datetime8: 'dd/MM/yyyy HH:mm',
    datetime9: 'dd/MM/yyyy HH:mm:ss',
    datetimeFigureOut: 'dd/MM/yyyy',
    uaqdatetime1: 'dd/MM/yyyy',
    uaqdatetime2: 'dddd, dd MMMM yyyy',
  },
  'en-US': {
    datetime: 'M/d/yyyy',
    datetime1: 'M/d/yyyy',
    datetime10: 'HH:mm',
    datetime11: 'HH:mm:ss',
    datetime12: 'h:mm tt',
    datetime13: 'h:mm:ss tt',
    datetime2: 'dddd, MMMM d, yyyy',
    datetime3: 'd MMMM yyyy',
    datetime4: 'MMMM d, yyyy',
    datetime5: 'd-MMM-yy',
    datetime6: 'MMMM yy',
    datetime7: 'MMM-yy',
    datetime8: 'M/d/yyyy h:mm tt',
    datetime9: 'M/d/yyyy h:mm:ss tt',
    datetimeFigureOut: 'M/d/yyyy',
    slidenum: 'h',
    uaqdatetime1: 'M/d/yyyy',
    uaqdatetime2: 'dddd, MMMM d, yyyy',
  },
  'es-ES': {
    datetime: 'dd/MM/yyyy',
    datetime1: 'dd/MM/yyyy',
    datetime10: 'HH:mm',
    datetime11: 'HH:mm:ss',
    datetime12: 'h:mm ',
    datetime13: 'h:mm:ss ',
    datetime3: 'dd.MM.yy',
    datetime8: 'dd/MM/yyyy HH:mm',
    datetime9: 'dd/MM/yyyy HH:mm:ss',
    datetimeFigureOut: 'dd/MM/yyyy',
    uaqdatetime1: 'dd/MM/yyyy',
  },
  'fr-FR': {
    datetime: 'dd/MM/yyyy',
    datetime1: 'dd/MM/yyyy',
    datetime10: 'HH:mm',
    datetime11: 'HH:mm:ss',
    datetime12: 'h:mm ',
    datetime13: 'h:mm:ss ',
    datetime2: 'dddd d MMMM yyyy',
    datetime3: 'dd.MM.yy',
    datetime4: 'd MMMM yyyy',
    datetime5: 'd-MMM-yy',
    datetime6: 'MMMM yy',
    datetime7: 'MMM-yy',
    datetime8: 'dd/MM/yyyy HH:mm',
    datetime9: 'dd/MM/yyyy HH:mm:ss',
    datetimeFigureOut: 'dd/MM/yyyy',
    uaqdatetime1: 'dd/MM/yyyy',
    uaqdatetime2: 'dddd d MMMM yyyy',
  },
  'he-IL': {
    datetime10: 'MMMM yy',
    datetime11: 'ddd dd MMMM yyyy',
    datetime12: 'dd/MM/yyyy HH:mm',
    datetime13: 'dd.MM.yyyy',
    datetime8: 'dd MMMM yy',
    datetime9: 'd MMMM, yyyy',
    uaqdatetime1: 'dd/MM/yyyy',
    uaqdatetime2: 'ddd dd MMMM yyyy',
  },
  'ja-JP': {
    datetime: 'M/d/yyyy',
    datetime1: 'M/d/yyyy',
    datetime10: 'HH:mm',
    datetime11: 'HH:mm:ss',
    datetimeFigureOut: 'M/d/yyyy',
    uaqdatetime1: 'M/d/yyyy',
  },
  'ko-KR': {
    datetime: 'M/d/yyyy',
    datetime1: 'M/d/yyyy',
    datetime10: 'HH:mm',
    datetime11: 'HH:mm:ss',
    datetime8: 'M/d/yyyy h:mm tt',
    datetime9: 'M/d/yyyy h:mm:ss tt',
    datetimeFigureOut: 'M/d/yyyy',
    uaqdatetime1: 'M/d/yyyy',
  },
  'pt-BR': {
    datetime: 'dd/MM/yyyy',
    datetime1: 'dd/MM/yyyy',
    datetime10: 'HH:mm',
    datetime11: 'HH:mm:ss',
    datetime12: 'h:mm ',
    datetime13: 'h:mm:ss ',
    datetime3: 'dd.MM.yy',
    datetime8: 'dd/MM/yyyy HH:mm',
    datetime9: 'dd/MM/yyyy HH:mm:ss',
    datetimeFigureOut: 'dd/MM/yyyy',
    uaqdatetime1: 'dd/MM/yyyy',
  },
  'ru-RU': {
    datetime: 'dd.MM.yyyy',
    datetime1: 'dd.MM.yyyy',
    datetime10: 'HH:mm',
    datetime11: 'HH:mm:ss',
    datetime12: 'h:mm ',
    datetime13: 'h:mm:ss ',
    datetime3: 'dd/MM/yy',
    datetime8: 'dd.MM.yyyy HH:mm',
    datetime9: 'dd.MM.yyyy HH:mm:ss',
    datetimeFigureOut: 'dd.MM.yyyy',
    uaqdatetime1: 'dd.MM.yyyy',
  },
  'tr-TR': {
    datetime: 'd.MM.yyyy',
    datetime1: 'd.MM.yyyy',
    datetime10: 'HH:mm',
    datetime11: 'HH:mm:ss',
    datetime12: 'h:mm tt',
    datetime13: 'h:mm:ss tt',
    datetime2: 'd MMMM yyyy dddd',
    datetime3: 'd/MM/yy',
    datetime4: 'd MMMM yyyy',
    datetime5: 'd-MMM-yy',
    datetime6: 'MMMM yy',
    datetime7: 'MMM-yy',
    datetime8: 'd.MM.yyyy HH:mm',
    datetime9: 'd.MM.yyyy HH:mm:ss',
    datetimeFigureOut: 'd.MM.yyyy',
    uaqdatetime1: 'd.MM.yyyy',
    uaqdatetime2: 'd MMMM yyyy dddd',
  },
  'vi-VN': {
    datetime: 'dd/MM/yyyy',
    datetime1: 'dd/MM/yyyy',
    datetime10: 'h:mm tt',
    datetime11: 'h:mm:ss tt',
    datetime12: 'HH:mm',
    datetime13: 'HH:mm:ss',
    datetime4: 'dd/MM/yy',
    datetime8: 'dd/MM/yyyy h:mm tt',
    datetime9: 'dd/MM/yyyy h:mm:ss tt',
    datetimeFigureOut: 'dd/MM/yyyy',
    uaqdatetime1: 'dd/MM/yyyy',
  },
  'zh-CN': {
    datetime: 'M/d/yyyy',
    datetime1: 'M/d/yyyy',
    datetime10: 'HH:mm',
    datetime11: 'HH:mm:ss',
    datetime7: 'yy.M.d',
    datetimeFigureOut: 'M/d/yyyy',
    uaqdatetime1: 'M/d/yyyy',
  },
};
