/**
 * `a:fld`: what a field shows, and where the answer comes from.
 *
 * ## The plan's design for this did not survive the measurement
 *
 * Sub-phase 3.5 was specified as "14 reserved `a:fld` types with
 * `Intl.DateTimeFormat` keyed on `@lang`, falling back to the cached text".
 * Three of those four clauses are wrong, and the fourth is right for a reason
 * the plan did not give:
 *
 * - **There are eighteen reserved types, not fourteen.** PowerPoint's own UI
 *   writes `datetime1` through `datetime13`, `datetimeFigureOut`, `slidenum`,
 *   and - undocumented in any enumeration this project has read - `uaqdatetime1`
 *   and `uaqdatetime2`, which are the Umm al-Qura calendar. ECMA-376 also
 *   reserves a bare `datetime`.
 * - **`Intl.DateTimeFormat` does not reproduce PowerPoint.** Scored against 97
 *   measured readings it agrees on 25. What PowerPoint does is format with
 *   **Windows' own per-locale patterns**, which is why `datetime3` is
 *   "5 September 2026" in one locale and "05/09/26" in the next, and why
 *   `datetime12` in German is "12:56 " - a pattern ending in an AM/PM
 *   designator that German defines as empty. So the patterns are a measured
 *   table, generated by `tools/ground-truth/text/bullets/write-tables.ts`.
 * - **The cached `a:t` is not what a reader displays.** A deck whose fields were
 *   overwritten with `#stale#` and reopened showed the real date every time, in
 *   290 readings; one reopened four minutes after it was written showed
 *   `12:04 PM` where the file said `12:02 PM`. The cache is a fallback for a
 *   reader that cannot compute, never the answer.
 * - **The fallback is right, and it is what an *unreserved* type gets.** A field
 *   typed `notAReservedType` rendered its cached text exactly.
 *
 * `corpus/ground-truth/bullets.json`, and
 * `docs/adr/phase-3-text/0031-bullets-fields-and-script-runs.md`.
 */

import { TextError } from '../errors.js';
import { FIELD_DATE_PATTERNS } from './field-formats.gen.js';

/**
 * The eighteen `@type` values PowerPoint treats as fields rather than as text.
 *
 * Seventeen were produced by PowerPoint itself, by inserting each
 * `PpDateTimeFormat` and reading the saved package; `datetime` is the one
 * ECMA-376 reserves that its UI never writes, so it is here as a value only
 * another producer can put in a file.
 */
export const RESERVED_FIELD_TYPES = [
  'slidenum',
  'datetime',
  'datetime1',
  'datetime2',
  'datetime3',
  'datetime4',
  'datetime5',
  'datetime6',
  'datetime7',
  'datetime8',
  'datetime9',
  'datetime10',
  'datetime11',
  'datetime12',
  'datetime13',
  'datetimeFigureOut',
  'uaqdatetime1',
  'uaqdatetime2',
] as const;

export type ReservedFieldType = (typeof RESERVED_FIELD_TYPES)[number];

const RESERVED: ReadonlySet<string> = new Set(RESERVED_FIELD_TYPES);

/** Whether PowerPoint recomputes this `@type` rather than showing the cache. */
export function isReservedFieldType(type: string): type is ReservedFieldType {
  return RESERVED.has(type);
}

/* -------------------------------------------------------------------------- */
/* the pattern language                                                       */
/* -------------------------------------------------------------------------- */

/**
 * A component's text in one locale, taken from a full date so it is in context.
 *
 * `toLocaleString(lang, { month: 'long' })` gives Russian "сентябрь", the
 * standalone nominative, and a Russian date says "сентября". `formatToParts`
 * over a whole date gives the form the locale uses inside one, which is the
 * string PowerPoint's own output holds - the derivation in
 * `tools/ground-truth/text/bullets/analyse.ts` only accepts a pattern that reproduces the measurement,
 * so this being right is what made 266 of the 290 cells derivable at all.
 */
function localePart(
  lang: string,
  at: Date,
  part: 'month' | 'weekday' | 'dayPeriod',
  width: 'long' | 'short',
): string {
  const options: Intl.DateTimeFormatOptions =
    part === 'dayPeriod'
      ? { hour: 'numeric', minute: '2-digit', hour12: true }
      : part === 'month'
        ? { day: 'numeric', month: width, year: 'numeric' }
        : { weekday: width, day: 'numeric', month: 'numeric', year: 'numeric' };
  const found = new Intl.DateTimeFormat(lang, options)
    .formatToParts(at)
    .find((piece) => piece.type === part);
  const value = found?.value ?? '';
  // A locale that writes its months as numbers - Japanese, Chinese, Korean -
  // has ICU return "9" for the long month name. Letting that stand as MMMM
  // produces a pattern that renders correctly and documents a lie, so a numeric
  // name is no name at all.
  return part === 'dayPeriod' || !/\p{Nd}/u.test(value) ? value : '';
}

const twelveHour = (hours: number): number => (hours % 12 === 0 ? 12 : hours % 12);

/** The tokens a measured pattern can hold, longest first so `MMMM` beats `MM`. */
const TOKENS: readonly (readonly [string, (at: Date, lang: string) => string])[] = [
  ['yyyy', (at) => String(at.getFullYear())],
  ['MMMM', (at, lang) => localePart(lang, at, 'month', 'long')],
  ['dddd', (at, lang) => localePart(lang, at, 'weekday', 'long')],
  ['MMM', (at, lang) => localePart(lang, at, 'month', 'short')],
  ['ddd', (at, lang) => localePart(lang, at, 'weekday', 'short')],
  ['yy', (at) => String(at.getFullYear() % 100).padStart(2, '0')],
  ['MM', (at) => String(at.getMonth() + 1).padStart(2, '0')],
  ['dd', (at) => String(at.getDate()).padStart(2, '0')],
  ['HH', (at) => String(at.getHours()).padStart(2, '0')],
  ['hh', (at) => String(twelveHour(at.getHours())).padStart(2, '0')],
  ['mm', (at) => String(at.getMinutes()).padStart(2, '0')],
  ['ss', (at) => String(at.getSeconds()).padStart(2, '0')],
  ['M', (at) => String(at.getMonth() + 1)],
  ['d', (at) => String(at.getDate())],
  ['H', (at) => String(at.getHours())],
  ['h', (at) => String(twelveHour(at.getHours()))],
  ['m', (at) => String(at.getMinutes())],
  ['s', (at) => String(at.getSeconds())],
  ['tt', (at, lang) => localePart(lang, at, 'dayPeriod', 'long')],
];

/** Render one measured Windows NLS pattern for an instant, in a locale. */
export function renderDatePattern(pattern: string, at: Date, lang: string): string {
  let out = '';
  for (let index = 0; index < pattern.length;) {
    const token = TOKENS.find(([name]) => pattern.startsWith(name, index));
    if (token === undefined) {
      out += pattern[index] ?? '';
      index++;
      continue;
    }
    out += token[1](at, lang);
    index += token[0].length;
  }
  return out;
}

/**
 * The measured pattern for a `@type` in a `@lang`, or `null` where none was.
 *
 * Falls back from `de-DE` to `de` and then gives up, because a deck may state
 * either and PowerPoint's own tables are keyed by full locale. It does **not**
 * fall back to `en-US`: showing an American date to a German reader because the
 * German cell is missing is exactly the silent wrong answer this table exists to
 * prevent, and `renderField` has a better fallback than that.
 */
export function datePatternFor(type: string, lang: string): string | null {
  const byLang = FIELD_DATE_PATTERNS[lang] ?? FIELD_DATE_PATTERNS[lang.split('-')[0] ?? ''];
  return byLang?.[type] ?? null;
}

/**
 * The text a date field shows, formatted the way PowerPoint formats it.
 *
 * Throws where the `(type, lang)` cell was never measured. That is the point:
 * twenty-four of the 290 measured cells could not even be turned back into a
 * pattern - the Japanese era calendar among them - so a caller that reaches this
 * for an unmeasured locale must not be handed a plausible date. `renderField`
 * is the function that knows what to do instead.
 */
export function formatDateTimeField(type: string, lang: string, at: Date): string {
  if (!isReservedFieldType(type) || type === 'slidenum') {
    throw new TextError('TEXT_FIELD', `${type} is not a date field type`, type);
  }
  const pattern = datePatternFor(type, lang);
  if (pattern === null) {
    throw new TextError(
      'TEXT_FIELD_LOCALE',
      `no measured date pattern for ${type} in ${lang}`,
      `${type}/${lang}`,
    );
  }
  return renderDatePattern(pattern, at, lang);
}

/* -------------------------------------------------------------------------- */
/* the whole field                                                            */
/* -------------------------------------------------------------------------- */

/** Everything `renderField` needs about one `a:fld`. */
export interface FieldRequest {
  /** `a:fld/@type`. An unreserved value is the cache's cue, not an error. */
  readonly type: string;
  /** The `@lang` of the field's own `a:rPr`, which is what drives the format. */
  readonly lang: string;
  /** The `a:t` PowerPoint last wrote, which is the fallback and never the answer. */
  readonly cachedText: string;
  /** The slide's one-based position, for `slidenum`. */
  readonly slideNumber?: number | undefined;
  /** The instant to render a date at. Passed in so a test is not a clock. */
  readonly now: Date;
}

/** What was shown, and which of the three branches produced it. */
export interface RenderedField {
  readonly text: string;
  /**
   * - `computed`: a reserved type with a measured pattern, recomputed as
   *   PowerPoint recomputes it.
   * - `cached`: the `a:t`, because the type is not reserved or its locale was
   *   never measured. Diagnosable, and the right thing to show.
   */
  readonly source: 'computed' | 'cached';
  /** Why the cache was used, for the diagnostics panel. Empty when it was not. */
  readonly reason: string;
}

/**
 * What to display for one `a:fld`.
 *
 * The ladder, in the order the measurement supports it:
 *
 * 1. `slidenum` is the slide's position. Measured on five slides, and the cached
 *    text - deliberately wrong in every probe - never appeared.
 * 2. A reserved date type with a measured `(type, lang)` pattern is recomputed.
 * 3. Everything else shows the cached text, which is what PowerPoint itself does
 *    for a type nothing reserves.
 */
export function renderField(request: FieldRequest): RenderedField {
  if (request.type === 'slidenum') {
    const number = request.slideNumber;
    if (number === undefined || !Number.isInteger(number) || number < 1) {
      throw new TextError(
        'TEXT_FIELD',
        `a slidenum field needs a one-based slide number, not ${String(number)}`,
        String(number),
      );
    }
    return { text: String(number), source: 'computed', reason: '' };
  }

  if (!isReservedFieldType(request.type)) {
    return {
      text: request.cachedText,
      source: 'cached',
      reason: `${request.type} is not a reserved field type`,
    };
  }

  const pattern = datePatternFor(request.type, request.lang);
  if (pattern === null) {
    return {
      text: request.cachedText,
      source: 'cached',
      reason: `no measured date pattern for ${request.type} in ${request.lang}`,
    };
  }
  return {
    text: renderDatePattern(pattern, request.now, request.lang),
    source: 'computed',
    reason: '',
  };
}
