/**
 * PowerPoint's built-in kinsoku sets, and the six characters that hang.
 *
 * GENERATED by tools/ground-truth/write-break-tables.ts from
 * corpus/ground-truth/line-breaks.json. Do not edit by hand.
 *
 * Measured, not transcribed. Each candidate was placed between two runs of
 * ideographs - which break freely - and the two positions either side of it
 * were read back from PowerPoint's own layout: the position before it is absent
 * when the character may not begin a line, the position after it is absent when
 * it may not end one. Six ordinary characters were included as controls and all
 * six came back unrestricted, which is what makes the other 90 readings mean
 * something.
 *
 * The widely repeated version of these sets is wrong in four places. It lists
 * \u00a2 (¢), \u00a3 (£), \u00a5 (¥), \uff03 (＃) as restricted; PowerPoint restricts none of
 * them, while restricting the fullwidth pound and yen the list leaves out.
 *
 * ## When these apply
 *
 * Always, unless a package *both* states its own `p:kinsoku` *and* sets
 * `p:presentation/@strictFirstAndLastChars="0"`. In that case the file's sets
 * replace these entirely - measured with empty sets, where every position in
 * every East Asian probe became a break opportunity, including before an
 * ideographic comma. There is no hard core that survives replacement.
 *
 * Stating `p:kinsoku` without turning strict off changes nothing at all, which
 * matters because that is what almost every real deck does.
 */

/** The two sets, as characters. */
export interface KinsokuSets {
  /** Characters that may not begin a line. */
  readonly noStart: ReadonlySet<string>;
  /** Characters that may not end a line. */
  readonly noEnd: ReadonlySet<string>;
}

const BUILT_IN_NO_START = [
  '\u0021\u0025\u0029\u002c\u002e\u003a\u003b\u003f', // ! % ) , . : ; ?
  '\u005d\u007d\u2019\u201d\u2030\u2032\u2033\u2103', // ] } ’ ” ‰ ′ ″ ℃
  '\u3001\u3002\u3005\u3009\u300b\u300d\u300f\u3011', // 、 。 々 〉 》 」 』 】
  '\u3015\u3041\u3043\u3045\u3047\u3049\u3063\u3083', // 〕 ぁ ぃ ぅ ぇ ぉ っ ゃ
  '\u3085\u3087\u308e\u309b\u309c\u309d\u309e\u30a1', // ゅ ょ ゎ ゛ ゜ ゝ ゞ ァ
  '\u30a3\u30a5\u30a7\u30a9\u30c3\u30e3\u30e5\u30e7', // ィ ゥ ェ ォ ッ ャ ュ ョ
  '\u30ee\u30f5\u30f6\u30fb\u30fc\u30fd\u30fe\uff01', // ヮ ヵ ヶ ・ ー ヽ ヾ ！
  '\uff05\uff09\uff0c\uff0e\uff1a\uff1b\uff1f\uff3d', // ％ ） ， ． ： ； ？ ］
  '\uff5d\uff61\uff63\uff64\uff65\uff9e\uff9f', // ｝ ｡ ｣ ､ ･ ﾞ ﾟ
].join('');

const BUILT_IN_NO_END = [
  '\u0024\u0028\u005b\u005c\u007b\u2018\u201c\u3008', // $ ( [ \ { ‘ “ 〈
  '\u300a\u300c\u300e\u3010\u3014\uff04\uff08\uff3b', // 《 「 『 【 〔 ＄ （ ［
  '\uff5b\uffe1\uffe5', // ｛ ￡ ￥
].join('');

/** PowerPoint's own sets, used unless a file replaces them. */
export const BUILT_IN_KINSOKU: KinsokuSets = {
  noStart: new Set([...BUILT_IN_NO_START]),
  noEnd: new Set([...BUILT_IN_NO_END]),
};

/**
 * The characters that hang outside the measure when `hangingPunct` is on.
 *
 * Exactly six: the comma and the full stop, each in its ASCII, ideographic and
 * fullwidth form. Nothing else hangs - not the closing brackets, not the small
 * kana, not the prolonged sound mark, all of which are start-forbidden and all
 * of which force a fallback rather than hanging.
 *
 * Every one of these is also in `noStart`, which is what makes hanging
 * coherent: a character that may not begin a line has to end the one before it,
 * and hanging is how it does that without widening the line.
 *
 * `a:pPr/@hangingPunct` defaults to **true** - measured, because ECMA does
 * not say.
 */
export const HANGING_PUNCTUATION: ReadonlySet<string> = new Set(
  [
    '\u002c\u002e\u3001\u3002\uff0c\uff0e', // , . 、 。 ， ．
  ].join(''),
);

/**
 * The sets in force, given what the package states.
 *
 * `stated` is `p:kinsoku` as the file holds it, or `undefined` when the file
 * has none - which is the common case and the reason this function exists
 * rather than the caller reaching for the file's sets directly.
 */
export function kinsokuInForce(
  stated: KinsokuSets | undefined,
  strictFirstAndLastChars: boolean | undefined,
): KinsokuSets {
  // Absent means strict, so only an explicit `0` hands control to the file.
  if (stated === undefined || strictFirstAndLastChars !== false) return BUILT_IN_KINSOKU;
  return stated;
}
