/**
 * The five compound strokes, as the fractions of `@w` they divide it into.
 *
 * GENERATED by tools/ground-truth/write-line-tables.ts from
 * corpus/ground-truth/lines.json. Do not edit by hand.
 *
 * Each entry alternates rail, gap, rail, ... from the **outside** of the shape
 * inwards, and every one of them sums to exactly one stroke width. That last
 * part is the useful finding: a compound stroke does not make the outline wider,
 * it subdivides the width already declared, so a renderer that draws two rails
 * of `@w` each is twice as heavy as PowerPoint and one that draws them inside a
 * band of `@w` is right.
 *
 * Measured across a 36pt outline at two pixels to the point. The first attempt
 * measured the *neighbouring* shape as well - a 36pt compound stroke reaches
 * 22pt outside its own rectangle - and reported an extra rail on every row.
 *
 * The numbers are whole **sixtieths** of the width rather than decimals, because
 * every one of them is a third, a fifth, a sixth or a tenth and sixtieths carry
 * all four exactly. `compoundRails` divides by sixty last, so a rail of a third
 * of a 36000 EMU stroke is 12000 and not 11999.988.
 */

/** Alternating rail and gap widths, in sixtieths of `a:ln/@w`, outside first. */
export const COMPOUND_RUNS_60: Readonly<Record<string, readonly number[]>> = {
  sng: [60],
  dbl: [20, 20, 20],
  thickThin: [36, 12, 12],
  thinThick: [12, 12, 36],
  tri: [10, 10, 20, 10, 10],
};

/** The same, as fractions - convenient to read, and not what the maths uses. */
export const COMPOUND_RUNS: Readonly<Record<string, readonly number[]>> = Object.fromEntries(
  Object.entries(COMPOUND_RUNS_60).map(([name, runs]) => [name, runs.map((r) => r / 60)]),
);

export const COMPOUND_NAMES: readonly string[] = ['sng', 'dbl', 'thickThin', 'thinThick', 'tri'];

/** Deliberately not a type predicate; see `isPresetDashName` for why. */
export function isCompoundName(name: string): boolean {
  return Object.hasOwn(COMPOUND_RUNS_60, name);
}
