/**
 * `ST_PresetColorVal`: 147 names, and the values PowerPoint paints for them.
 *
 * Measured, not transcribed. Sub-phase 2.6 put one swatch per name in front of
 * PowerPoint and read the pixels back - `corpus/ground-truth/color-bases.json`,
 * and `preset-colors.test.ts` re-derives this table from that fixture so the two
 * cannot drift. Two things came out of doing it that way rather than copying a
 * table out of another project:
 *
 *   - **All 147 opened without a repair prompt**, which is how we know the
 *     enumeration really does carry both the `Gray` and the `Grey` spelling of
 *     the seven grey names. Nobody here has read the schema.
 *   - The table carries nobody's copyright. It is a measurement of a program.
 *
 * ## They are not CSS colour names
 *
 * Not one of these 147 is a name a browser will accept. DrawingML abbreviates -
 * `dkBlue`, `ltGray`, `medOrchid`, `ltGoldenrodYellow` - where CSS spells the
 * words out, so handing `@val` straight to `color:` yields no colour at all
 * rather than the wrong one. The mapping is not purely mechanical either:
 * `dkGrey` and `dkGray` are distinct enumeration values here and a single
 * `darkgray`/`darkgrey` alias pair in CSS.
 *
 * On values, one is worth naming because it is the classic trap: `gray` is
 * `808080`, the HTML/CSS value, not X11's `BEBEBE`. Whether any of the other 146
 * differs from the X11 value of its expanded name is not measured here - the
 * table above is what PowerPoint paints, which is the only thing this package
 * needs to know.
 */
export const PRESET_COLORS: Readonly<Record<string, string>> = {
  aliceBlue: 'F0F8FF',
  antiqueWhite: 'FAEBD7',
  aqua: '00FFFF',
  aquamarine: '7FFFD4',
  azure: 'F0FFFF',
  beige: 'F5F5DC',
  bisque: 'FFE4C4',
  black: '000000',
  blanchedAlmond: 'FFEBCD',
  blue: '0000FF',
  blueViolet: '8A2BE2',
  brown: 'A52A2A',
  burlyWood: 'DEB887',
  cadetBlue: '5F9EA0',
  chartreuse: '7FFF00',
  chocolate: 'D2691E',
  coral: 'FF7F50',
  cornflowerBlue: '6495ED',
  cornsilk: 'FFF8DC',
  crimson: 'DC143C',
  cyan: '00FFFF',
  dkBlue: '00008B',
  dkCyan: '008B8B',
  dkGoldenrod: 'B8860B',
  dkGray: 'A9A9A9',
  dkGreen: '006400',
  dkKhaki: 'BDB76B',
  dkMagenta: '8B008B',
  dkOliveGreen: '556B2F',
  dkOrange: 'FF8C00',
  dkOrchid: '9932CC',
  dkRed: '8B0000',
  dkSalmon: 'E9967A',
  dkSeaGreen: '8FBC8F',
  dkSlateBlue: '483D8B',
  dkSlateGray: '2F4F4F',
  dkTurquoise: '00CED1',
  dkViolet: '9400D3',
  deepPink: 'FF1493',
  deepSkyBlue: '00BFFF',
  dimGray: '696969',
  dodgerBlue: '1E90FF',
  firebrick: 'B22222',
  floralWhite: 'FFFAF0',
  forestGreen: '228B22',
  fuchsia: 'FF00FF',
  gainsboro: 'DCDCDC',
  ghostWhite: 'F8F8FF',
  gold: 'FFD700',
  goldenrod: 'DAA520',
  gray: '808080',
  green: '008000',
  greenYellow: 'ADFF2F',
  honeydew: 'F0FFF0',
  hotPink: 'FF69B4',
  indianRed: 'CD5C5C',
  indigo: '4B0082',
  ivory: 'FFFFF0',
  khaki: 'F0E68C',
  lavender: 'E6E6FA',
  lavenderBlush: 'FFF0F5',
  lawnGreen: '7CFC00',
  lemonChiffon: 'FFFACD',
  ltBlue: 'ADD8E6',
  ltCoral: 'F08080',
  ltCyan: 'E0FFFF',
  ltGoldenrodYellow: 'FAFAD2',
  ltGray: 'D3D3D3',
  ltGreen: '90EE90',
  ltPink: 'FFB6C1',
  ltSalmon: 'FFA07A',
  ltSeaGreen: '20B2AA',
  ltSkyBlue: '87CEFA',
  ltSlateGray: '778899',
  ltSteelBlue: 'B0C4DE',
  ltYellow: 'FFFFE0',
  lime: '00FF00',
  limeGreen: '32CD32',
  linen: 'FAF0E6',
  magenta: 'FF00FF',
  maroon: '800000',
  medAquamarine: '66CDAA',
  medBlue: '0000CD',
  medOrchid: 'BA55D3',
  medPurple: '9370DB',
  medSeaGreen: '3CB371',
  medSlateBlue: '7B68EE',
  medSpringGreen: '00FA9A',
  medTurquoise: '48D1CC',
  medVioletRed: 'C71585',
  midnightBlue: '191970',
  mintCream: 'F5FFFA',
  mistyRose: 'FFE4E1',
  moccasin: 'FFE4B5',
  navajoWhite: 'FFDEAD',
  navy: '000080',
  oldLace: 'FDF5E6',
  olive: '808000',
  oliveDrab: '6B8E23',
  orange: 'FFA500',
  orangeRed: 'FF4500',
  orchid: 'DA70D6',
  paleGoldenrod: 'EEE8AA',
  paleGreen: '98FB98',
  paleTurquoise: 'AFEEEE',
  paleVioletRed: 'DB7093',
  papayaWhip: 'FFEFD5',
  peachPuff: 'FFDAB9',
  peru: 'CD853F',
  pink: 'FFC0CB',
  plum: 'DDA0DD',
  powderBlue: 'B0E0E6',
  purple: '800080',
  red: 'FF0000',
  rosyBrown: 'BC8F8F',
  royalBlue: '4169E1',
  saddleBrown: '8B4513',
  salmon: 'FA8072',
  sandyBrown: 'F4A460',
  seaGreen: '2E8B57',
  seaShell: 'FFF5EE',
  sienna: 'A0522D',
  silver: 'C0C0C0',
  skyBlue: '87CEEB',
  slateBlue: '6A5ACD',
  slateGray: '708090',
  snow: 'FFFAFA',
  springGreen: '00FF7F',
  steelBlue: '4682B4',
  tan: 'D2B48C',
  teal: '008080',
  thistle: 'D8BFD8',
  tomato: 'FF6347',
  turquoise: '40E0D0',
  violet: 'EE82EE',
  wheat: 'F5DEB3',
  white: 'FFFFFF',
  whiteSmoke: 'F5F5F5',
  yellow: 'FFFF00',
  yellowGreen: '9ACD32',
  dkGrey: 'A9A9A9',
  dimGrey: '696969',
  dkSlateGrey: '2F4F4F',
  grey: '808080',
  ltGrey: 'D3D3D3',
  ltSlateGrey: '778899',
  slateGrey: '708090',
};

/** Whether a token is one of the 147. */
export function isPresetColorName(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(PRESET_COLORS, name);
}
