/**
 * Turn the T3 fixture into the kinsoku table `@pptx-studio/text` ships.
 *
 * ```
 * node tools/ground-truth/text/line-breaks/write-tables.ts
 * ```
 *
 * Writes `packages/text/src/lines/kinsoku.ts` from `corpus/ground-truth/line-breaks.json`.
 * The table is not hand-written and may not be hand-edited: `break.test.ts`
 * re-derives it from the same fixture and fails if the two have drifted, which
 * is the only thing standing between a measured constant and somebody's memory
 * of one.
 *
 * There is a specific reason this table is measured rather than copied. The
 * "standard Japanese kinsoku sets" as they appear in `a10-rtl-cjk`'s comment -
 * and in a good deal of prose about the format - get four characters wrong:
 * they list the halfwidth cent, pound, yen and fullwidth number sign as
 * restricted, and PowerPoint does not restrict any of them, while it does
 * restrict the *fullwidth* pound and yen that the list omits. Every character
 * here was put between two ideographs and asked.
 */

import { readFileSync, writeFileSync } from 'node:fs';

interface Fixture {
  readonly kinsoku: {
    readonly mayNotBeginLine: readonly string[];
    readonly mayNotEndLine: readonly string[];
    readonly hangOutsideTheMeasure: readonly string[];
    readonly unrestrictedControls: readonly string[];
    readonly disagreesWithA10Comment: readonly string[];
  };
  readonly rules: {
    readonly flagDefaults: Readonly<Record<string, string>>;
  };
}

const fixture = JSON.parse(readFileSync('corpus/ground-truth/line-breaks.json', 'utf8')) as Fixture;

const { mayNotBeginLine, mayNotEndLine, hangOutsideTheMeasure } = fixture.kinsoku;

/**
 * A character as a `\u` escape.
 *
 * Never as itself. A fullwidth comma and an ideographic comma are one pixel
 * apart on screen and are different entries in this table; a reader has to be
 * able to tell which one a row is, and so does a diff.
 */
function esc(ch: string): string {
  const cp = ch.codePointAt(0) ?? 0;
  return `\\u${cp.toString(16).padStart(4, '0')}`;
}

/** A set literal, wrapped at a readable width, with the characters in a trailing comment. */
function setOf(chars: readonly string[]): string {
  const rows: string[] = [];
  for (let i = 0; i < chars.length; i += 8) {
    const chunk = chars.slice(i, i + 8);
    rows.push(`  '${chunk.map(esc).join('')}', // ${chunk.join(' ')}`);
  }
  return rows.join('\n');
}

const source = `/**
 * PowerPoint's built-in kinsoku sets, and the six characters that hang.
 *
 * GENERATED by tools/ground-truth/text/line-breaks/write-tables.ts from
 * corpus/ground-truth/line-breaks.json. Do not edit by hand.
 *
 * Measured, not transcribed. Each candidate was placed between two runs of
 * ideographs - which break freely - and the two positions either side of it
 * were read back from PowerPoint's own layout: the position before it is absent
 * when the character may not begin a line, the position after it is absent when
 * it may not end one. Six ordinary characters were included as controls and all
 * six came back unrestricted, which is what makes the other ${String(
   mayNotBeginLine.length + mayNotEndLine.length,
 )} readings mean
 * something.
 *
 * The widely repeated version of these sets is wrong in four places. It lists
 * ${fixture.kinsoku.disagreesWithA10Comment.map((c) => `${esc(c)} (${c})`).join(', ')} as restricted; PowerPoint restricts none of
 * them, while restricting the fullwidth pound and yen the list leaves out.
 *
 * ## When these apply
 *
 * Always, unless a package *both* states its own \`p:kinsoku\` *and* sets
 * \`p:presentation/@strictFirstAndLastChars="0"\`. In that case the file's sets
 * replace these entirely - measured with empty sets, where every position in
 * every East Asian probe became a break opportunity, including before an
 * ideographic comma. There is no hard core that survives replacement.
 *
 * Stating \`p:kinsoku\` without turning strict off changes nothing at all, which
 * matters because that is what almost every real deck does.
 */

/** The two sets, as characters. */
export interface KinsokuSets {
  /** Characters that may not begin a line. */
  readonly noStart: ReadonlySet<string>;
  /** Characters that may not end a line. */
  readonly noEnd: ReadonlySet<string>;
}

const BUILT_IN_NO_START = [
${setOf(mayNotBeginLine)}
].join('');

const BUILT_IN_NO_END = [
${setOf(mayNotEndLine)}
].join('');

/** PowerPoint's own sets, used unless a file replaces them. */
export const BUILT_IN_KINSOKU: KinsokuSets = {
  noStart: new Set([...BUILT_IN_NO_START]),
  noEnd: new Set([...BUILT_IN_NO_END]),
};

/**
 * The characters that hang outside the measure when \`hangingPunct\` is on.
 *
 * Exactly six: the comma and the full stop, each in its ASCII, ideographic and
 * fullwidth form. Nothing else hangs - not the closing brackets, not the small
 * kana, not the prolonged sound mark, all of which are start-forbidden and all
 * of which force a fallback rather than hanging.
 *
 * Every one of these is also in \`noStart\`, which is what makes hanging
 * coherent: a character that may not begin a line has to end the one before it,
 * and hanging is how it does that without widening the line.
 *
 * \`a:pPr/@hangingPunct\` defaults to **${fixture.rules.flagDefaults['hangingPunct'] ?? '?'}** - measured, because ECMA does
 * not say.
 */
export const HANGING_PUNCTUATION: ReadonlySet<string> = new Set([
${setOf(hangOutsideTheMeasure)}
].join(''));

/**
 * The sets in force, given what the package states.
 *
 * \`stated\` is \`p:kinsoku\` as the file holds it, or \`undefined\` when the file
 * has none - which is the common case and the reason this function exists
 * rather than the caller reaching for the file's sets directly.
 */
export function kinsokuInForce(
  stated: KinsokuSets | undefined,
  strictFirstAndLastChars: boolean | undefined,
): KinsokuSets {
  // Absent means strict, so only an explicit \`0\` hands control to the file.
  if (stated === undefined || strictFirstAndLastChars !== false) return BUILT_IN_KINSOKU;
  return stated;
}
`;

writeFileSync('packages/text/src/lines/kinsoku.ts', source);
console.log('wrote packages/text/src/lines/kinsoku.ts');
console.log(
  `  ${String(mayNotBeginLine.length)} may not begin a line, ` +
    `${String(mayNotEndLine.length)} may not end one, ` +
    `${String(hangOutsideTheMeasure.length)} hang`,
);
