/**
 * Turn the C8 fixture into the tables `@pptx-studio/model` and `@pptx-studio/validate` ship.
 *
 * ```
 * node tools/ground-truth/model/tables/styles/write-tables.ts
 * ```
 *
 * Writes `packages/model/src/builtin/table-styles.ts` and
 * `packages/validate/src/rules/table-style-ids.ts`; each package's tests re-derive its table.
 */

import { readFileSync, writeFileSync } from 'node:fs';

import { repoPath } from '../../../../repo/root.ts';

interface Fixture {
  readonly roster: { readonly styles: readonly { readonly name: string; readonly id: string }[] };
  readonly definitions: Readonly<Record<string, string>>;
}

const FIXTURE = 'corpus/ground-truth/table-styles.json';
const fixture = JSON.parse(readFileSync(repoPath(FIXTURE), 'utf8')) as Fixture;
const GUID = /^\{[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\}$/;

const styles = fixture.roster.styles.map(({ id, name }) => {
  const xml = fixture.definitions[id];
  if (xml === undefined) throw new Error(`${name} has no definition`);
  if (!GUID.test(id)) throw new Error(`${name}: ${id} is not an upper-case ST_Guid`);
  if (!xml.startsWith(`<a:tblStyle styleId="${id}" styleName="${name}">`)) {
    throw new Error(`${name}'s definition does not name it`);
  }
  return { id, name, xml };
});
if (styles.length !== 74 || new Set(styles.map((s) => s.id)).size !== 74) {
  throw new Error(`the roster has ${String(styles.length)} styles, not 74 distinct ones`);
}

const header = (test: string, what: string): string =>
  `/**\n * ${what}\n * GENERATED by tools/ground-truth/model/tables/styles/write-tables.ts from\n * ${FIXTURE}. Do not edit: ${test} re-derives it.\n */\n`;

const model =
  header(
    'table.test.ts',
    "PowerPoint's 74 built-in table styles, each `a:tblStyle` byte for byte as PowerPoint writes it.",
  ) +
  `
export interface BuiltinTableStyle {
  readonly id: string;
  readonly name: string;
  /** The \`a:tblStyle\` PowerPoint writes into \`ppt/tableStyles.xml\` for this style. */
  readonly xml: string;
}

/** In the order of PowerPoint's Table Styles gallery. */
export const BUILTIN_TABLE_STYLES: readonly BuiltinTableStyle[] = [
${styles.map((s) => `  { id: ${JSON.stringify(s.id)}, name: ${JSON.stringify(s.name)}, xml: ${JSON.stringify(s.xml)} },`).join('\n')}
];
`;

const validate =
  header(
    'rules.test.ts',
    "The GUIDs of PowerPoint's 74 built-in table styles, in its gallery's order.",
  ) +
  `
export const BUILTIN_TABLE_STYLE_IDS: readonly string[] = [
${styles.map((s) => `  ${JSON.stringify(s.id)},`).join('\n')}
];
`;

writeFileSync(repoPath('packages/model/src/builtin/table-styles.ts'), model);
writeFileSync(repoPath('packages/validate/src/rules/table-style-ids.ts'), validate);
console.log(
  'wrote packages/model/src/builtin/table-styles.ts and packages/validate/src/rules/table-style-ids.ts',
);
