/* Generated by tools/ground-truth/render/text/write-tables.ts. Do not edit. */

/** One rule, as fractions of the em: how far below the baseline, and how thick. */
export interface RuleMetrics {
  /** Below the baseline is positive, so a strikethrough's offset is negative. */
  readonly offset: number;
  readonly thickness: number;
}

/** The two rules a typeface carries. */
export interface FaceRules {
  readonly underline: RuleMetrics;
  readonly strike: RuleMetrics;
}

/**
 * Where PowerPoint drew each rule, measured at 120pt on a 1920-pixel export.
 *
 * 8 face(s). Chromium's own `text-decoration` matches none of them.
 */
export const MEASURED_FACE_RULES: Readonly<Record<string, FaceRules>> = {
  "Arial": {
    underline: { offset: 0.103, thickness: 0.075 },
    strike: { offset: -0.2595, thickness: 0.05 },
  },
  "Calibri": {
    underline: { offset: 0.114, thickness: 0.066667 },
    strike: { offset: -0.2485, thickness: 0.066667 },
  },
  "Consolas": {
    underline: { offset: 0.127833, thickness: 0.070833 },
    strike: { offset: -0.251333, thickness: 0.05 },
  },
  "Courier New": {
    underline: { offset: 0.234667, thickness: 0.041667 },
    strike: { offset: -0.257, thickness: 0.05 },
  },
  "Georgia": {
    underline: { offset: 0.086167, thickness: 0.05 },
    strike: { offset: -0.293, thickness: 0.05 },
  },
  "Tahoma": {
    underline: { offset: 0.084167, thickness: 0.0625 },
    strike: { offset: -0.336667, thickness: 0.0625 },
  },
  "Times New Roman": {
    underline: { offset: 0.109, thickness: 0.05 },
    strike: { offset: -0.257667, thickness: 0.05 },
  },
  "Verdana": {
    underline: { offset: 0.086167, thickness: 0.058333 },
    strike: { offset: -0.334667, thickness: 0.058333 },
  },
};
