/**
 * Experiment C7, step 4 - commit what PowerPoint painted.
 *
 * ```
 * node tools/ground-truth/render/pictures/write-tables.ts <work-dir>
 * ```
 *
 * Writes `corpus/ground-truth/pictures.json`: every sampled colour, the two
 * outline profiles, and the reading that survived. The tests read the samples
 * and re-derive the rule, so a renderer that stops obeying it fails against
 * PowerPoint rather than against a restatement of our own code.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { repoPath } from '../../../repo/root.ts';
import { readBmp, hex } from '../../lib/bmp.ts';
import { SLIDE_WIDTH } from '../../lib/pptx.ts';
import { OUTLINE_PT, pictureProbes, PT, SAMPLES, shapeControl, type Rect } from './probes.ts';

const dir = process.argv[2];
if (dir === undefined) {
  throw new Error('usage: node tools/ground-truth/render/pictures/write-tables.ts <work-dir>');
}

const readings = JSON.parse(readFileSync(join(dir, 'picture-readings.json'), 'utf8')) as {
  readonly powerPoint: { readonly version: string; readonly build: string };
};

const bitmap = readBmp(readFileSync(join(dir, 'shots', 'pictures-01-1920.bmp')));
const scale = bitmap.width / SLIDE_WIDTH;

function band(rect: Rect): { readonly outsidePt: number; readonly insidePt: number } {
  const y = Math.round((rect.y + 0.3 * rect.cy) * scale);
  const left = Math.round(rect.x * scale);
  const perPoint = PT * scale;
  const isLine = (x: number): boolean => hex(bitmap.pixel(x, y)) === 'FF00FF';
  let outside = 0;
  while (isLine(left - outside - 1)) outside++;
  let inside = 0;
  while (isLine(left + inside)) inside++;
  return { outsidePt: outside / perPoint, insidePt: inside / perPoint };
}

const probes = pictureProbes();
const table = {
  $comment: 'GENERATED by tools/ground-truth/render/pictures/write-tables.ts. Do not edit by hand.',
  experiment: 'C7',
  adr: 'phase-2-geometry-and-paint/0037-picture-shapes.md',
  powerPoint: readings.powerPoint,
  exportWidth: bitmap.width,
  /** The reading the analysis left standing, all 23 rivals refuted at 255. */
  rule: {
    clip: 'geometry',
    precedence: 'blip',
    outline: 'outside',
    mirror: 'image',
  },
  outlinePt: OUTLINE_PT,
  outlineBands: {
    picture: band(probes.find((probe) => probe.id === 'outline-thick')!.rect),
    shape: band(shapeControl().rect),
  },
  samples: probes.map((probe) => ({
    id: probe.id,
    question: probe.question,
    prst: probe.prst,
    flipH: probe.flipH,
    flipV: probe.flipV,
    spPrFill: probe.spPrFill !== undefined,
    line: probe.line !== undefined,
    at: Object.fromEntries(
      SAMPLES.map((sample) => {
        const x = Math.round((probe.rect.x + sample.u * probe.rect.cx) * scale);
        const y = Math.round((probe.rect.y + sample.v * probe.rect.cy) * scale);
        return [sample.id, hex(bitmap.pixel(x, y))];
      }),
    ),
  })),
};

const out = repoPath('corpus/ground-truth/pictures.json');
writeFileSync(out, `${JSON.stringify(table, null, 2)}\n`);
console.log(
  `wrote ${out}: ${String(probes.length)} probes, ${String(SAMPLES.length)} samples each`,
);
