/**
 * PowerPoint's own `p:txStyles`, substituted when a master declares none.
 *
 * GENERATED by tools/ground-truth/write-text-tables.ts from
 * corpus/ground-truth/text-cascade.json. Do not edit by hand.
 *
 * Measured, not transcribed. Nine paragraphs at `lvl="0"` through `lvl="8"` in a
 * title placeholder, a body placeholder and a shape that is not a placeholder,
 * in a package whose master carries no `p:txStyles` at all, read back through
 * PowerPoint's own object model. The body ladder - 28, 24, 20 and then 18 for
 * the rest - is not a number anything in the file declares, which is how the
 * ladder experiment discovered there was a source below every source the plan
 * names.
 *
 * A PowerPoint-authored master always writes `p:txStyles`, so this table only
 * ever applies to a hand-written or damaged one. It exists because the
 * alternative is a placeholder resolving to no size at all, and because a
 * measured answer costs one deck.
 *
 * Only the three properties 3.1 resolves are recorded. `bullet` says whether
 * PowerPoint drew one, which is what 3.5 will need to reproduce; the glyph and
 * its font belong to that sub-phase and are in the fixture, not here.
 */

/** One level of a built-in list style. */
export interface BuiltinLevel {
  /** Hundredths of a point, as `a:defRPr/@sz` holds it. */
  readonly sz: number;
  /** EMU, as `a:lvlNpPr/@marL` holds it. */
  readonly marL: number;
  /** EMU, as `a:lvlNpPr/@indent` holds it. Negative is a hanging indent. */
  readonly indent: number;
  readonly bullet: boolean;
}

/** The three buckets, nine levels each, level 1 first. */
export const BUILTIN_TEXT_STYLES: {
  readonly title: readonly BuiltinLevel[];
  readonly body: readonly BuiltinLevel[];
  readonly other: readonly BuiltinLevel[];
} = {
  title: [
    { sz: 4400, marL: 0, indent: 0, bullet: false },
    { sz: 1800, marL: 0, indent: 0, bullet: false },
    { sz: 1800, marL: 0, indent: 0, bullet: false },
    { sz: 1800, marL: 0, indent: 0, bullet: false },
    { sz: 1800, marL: 0, indent: 0, bullet: false },
    { sz: 1800, marL: 0, indent: 0, bullet: false },
    { sz: 1800, marL: 0, indent: 0, bullet: false },
    { sz: 1800, marL: 0, indent: 0, bullet: false },
    { sz: 1800, marL: 0, indent: 0, bullet: false },
  ],
  body: [
    { sz: 2800, marL: 228600, indent: -228600, bullet: true },
    { sz: 2400, marL: 685800, indent: -228600, bullet: true },
    { sz: 2000, marL: 1143000, indent: -228600, bullet: true },
    { sz: 1800, marL: 1600200, indent: -228600, bullet: true },
    { sz: 1800, marL: 2057400, indent: -228600, bullet: true },
    { sz: 1800, marL: 2514600, indent: -228600, bullet: true },
    { sz: 1800, marL: 2971800, indent: -228600, bullet: true },
    { sz: 1800, marL: 3429000, indent: -228600, bullet: true },
    { sz: 1800, marL: 3886200, indent: -228600, bullet: true },
  ],
  other: [
    { sz: 1800, marL: 0, indent: 0, bullet: false },
    { sz: 1800, marL: 457200, indent: 0, bullet: false },
    { sz: 1800, marL: 914400, indent: 0, bullet: false },
    { sz: 1800, marL: 1371600, indent: 0, bullet: false },
    { sz: 1800, marL: 1828800, indent: 0, bullet: false },
    { sz: 1800, marL: 2286000, indent: 0, bullet: false },
    { sz: 1800, marL: 2743200, indent: 0, bullet: false },
    { sz: 1800, marL: 3200400, indent: 0, bullet: false },
    { sz: 1800, marL: 3657600, indent: 0, bullet: false },
  ],
};

/**
 * What is left when every source is silent and the master *does* declare
 * `p:txStyles`.
 *
 * Distinct from the table above, and measured separately: a body placeholder
 * whose `p:bodyStyle/a:lvl1pPr` declares only a `marL` came back at
 * 18 points rather than the built-in body style's
 * 28, and with no indent rather than the built-in's
 * hanging one. So the built-in styles are substituted wholesale for an absent
 * `p:txStyles` and are not a per-property backstop underneath a present one.
 *
 * `marL` and `indent` are **0**, not the ECMA-376 schema defaults of 347663 and
 * -342900. Materialising those at parse time gives every paragraph a
 * 27-point hanging indent nothing asked for, and blocks the inherited value on
 * top of it, because a default that has been written down cannot be told from a
 * declaration.
 */
export const TEXT_FLOOR: BuiltinLevel = {
  sz: 1800,
  marL: 0,
  indent: 0,
  bullet: false,
};
