#!/usr/bin/env node
/**
 * Write the Tier A probe decks, and the manifest that claims them.
 *
 * ```
 * node tools/corpus/tiers/a-generated/build-probes.ts --out corpus/decks --manifest
 * node tools/corpus/tiers/a-generated/build-probes.ts --out <scratch> --id a03-fills
 * node tools/corpus/tiers/a-generated/build-probes.ts --check --out corpus/decks
 * ```
 *
 * `--out` has no default, and that is a rule rather than an oversight:
 * `C008-orphan` fails on any file under `corpus/` that no manifest claims, so
 * a generator that wrote there by accident would break the gate for whoever ran
 * it next. Pointing it at `corpus/decks` is a deliberate act.
 *
 * `--check` rebuilds every deck and compares against what is on disk without
 * writing anything. That is `C-REGEN`: committed bytes and a recipe that
 * reproduces them are two different claims, and only one of them is checked by
 * hashing the file.
 *
 * The manifest is generated rather than hand-written, and everything in it
 * comes from a reviewed source: `description` and `features` are literals in
 * the deck's own module, which is code and is read in review; `sha256` and
 * `bytes` are measured from the file. Nothing is typed twice, and `C017-sorted`
 * holds by construction.
 */

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { REPO_ROOT as ROOT } from '../../../repo/root.ts';
import { buildProbePackage } from './markup/chassis.ts';
import { PROBE_DECKS } from './decks/index.ts';
import { outputName, type ProbeDeck } from './markup/types.ts';

interface Options {
  readonly out: string;
  readonly only: string | null;
  readonly manifest: boolean;
  readonly check: boolean;
}

function parseArgs(argv: readonly string[]): Options {
  let out = '';
  let only: string | null = null;
  let manifest = false;
  let check = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--out') out = argv[++i] ?? '';
    else if (arg === '--id') only = argv[++i] ?? null;
    else if (arg === '--manifest') manifest = true;
    else if (arg === '--check') check = true;
    else throw new Error('unknown argument ' + String(arg));
  }
  if (out === '') {
    throw new Error('--out <dir> is required: this generator defaults nowhere. See the header.');
  }
  return { out, only, manifest, check };
}

const options = parseArgs(process.argv.slice(2));
const outDir = resolve(ROOT, options.out);
const decks =
  options.only === null ? PROBE_DECKS : PROBE_DECKS.filter((d) => d.id === options.only);
if (decks.length === 0) throw new Error('no deck matches --id ' + String(options.only));

interface Built {
  readonly deck: ProbeDeck;
  readonly bytes: Uint8Array;
  readonly sha256: string;
  readonly entries: number;
  readonly slides: number;
}

function build(deck: ProbeDeck): Built {
  const spec = deck.build();
  const { bytes, entries } = buildProbePackage(spec);
  return {
    deck,
    bytes,
    sha256: createHash('sha256').update(bytes).digest('hex'),
    entries,
    slides: spec.slides.length,
  };
}

const built = decks.map(build);

if (options.check) {
  let bad = 0;
  for (const item of built) {
    const path = join(outDir, outputName(item.deck));
    let onDisk: Uint8Array;
    try {
      onDisk = new Uint8Array(readFileSync(path));
    } catch {
      console.error('  MISSING  ' + item.deck.id);
      bad += 1;
      continue;
    }
    const hash = createHash('sha256').update(onDisk).digest('hex');
    if (hash === item.sha256) continue;
    console.error(
      '  DIFFERS  ' + item.deck.id + '\n    on disk ' + hash + '\n    rebuilt ' + item.sha256,
    );
    bad += 1;
  }
  if (bad > 0) {
    console.error('\ncorpus: ' + String(bad) + ' deck(s) do not rebuild to their committed bytes');
    process.exit(1);
  }
  console.log('corpus: ' + String(built.length) + ' deck(s) rebuild byte-for-byte');
  process.exit(0);
}

mkdirSync(outDir, { recursive: true });
for (const item of built) {
  writeFileSync(join(outDir, outputName(item.deck)), item.bytes);
  console.log(
    '  ' +
      item.deck.id.padEnd(16) +
      String(item.bytes.byteLength).padStart(8) +
      ' bytes  ' +
      String(item.entries).padStart(3) +
      ' entries  ' +
      item.sha256.slice(0, 16),
  );
}

if (options.manifest) {
  if (options.only !== null) {
    throw new Error('--manifest writes every entry, so it cannot be combined with --id');
  }
  const manifest = {
    $comment:
      'Tier A of the sub-phase 1.1 corpus: decks this repository generates, committed as bytes ' +
      'and reproducible from the recipe. Generated by tools/corpus/tiers/a-generated/build-probes.ts --manifest; ' +
      'every description and features map is a literal in the deck module it describes.',
    manifestVersion: 1,
    collection: 'decks',
    generatedIn: '1.1',
    adr: 'docs/adr/phase-1-round-trip/0009-the-corpus.md',
    generator: 'tools/corpus/tiers/a-generated/build-probes.ts',
    // C018, and the reason the container is not this generator: the chassis
    // hands its entries to writeZip and decides no header field itself, so two
    // decks whose containers both came out of writeZip are one piece of
    // evidence about ZIP conventions whichever generator called it.
    serializers: { xml: 'tools/corpus/gen', container: 'tools/ground-truth/lib/zip.ts' },
    // Forty-one, not the roster's original forty-two. `a28-model3d` is cut and
    // `model3d` is declared below, which is the outcome ROSTER.md wrote down for
    // the case where E4 is not run.
    targetCount: 42,
    // C019, and the last of the four named rules. The array lives here because
    // Tier A is the tier that would have covered the key: the slot that is
    // missing is `a28-model3d`, and whoever builds it deletes this entry in the
    // same commit - C019 fails if they do not, so the file cannot go on
    // apologising for a hole that was filled.
    uncovered: [
      {
        key: 'model3d',
        why:
          'The a:ext GUID that carries am3d:model3d appears in no public specification. ' +
          "Microsoft's own Open XML SDK documents the element and its namespace " +
          '(DocumentFormat.OpenXml.Office2019.Drawing.Model3D, serialized am3d:model3d) but ' +
          'not the extension URI that hosts it, nor the relationship type and content type of ' +
          'the model part beside it. Guessing the four is worse than the hole, and a34-extlst is ' +
          'the deck that says why: an unknown a:ext/@uri is carried through untouched, so a ' +
          'fabricated GUID would open, render its raster and survive every resave with PowerPoint ' +
          "treating the extension as somebody else's. Nothing here would ever contradict it, and " +
          'this rule would read green.',
        closes:
          'Experiment E4 - insert a 3-D model in PowerPoint 16.0.20326 and read the extension ' +
          "back out. Blocked, and not on effort: PowerPoint's 3-D gallery fetches a " +
          'Microsoft-licensed model over the network, which is a download nobody has approved. ' +
          'Inserting a model authored here would avoid that; whether PowerPoint accepts one is ' +
          'the first thing E4 would find out. The Tier A slot is a28-model3d.',
      },
    ],
    entries: [...built]
      .sort((a, b) => a.deck.id.localeCompare(b.deck.id))
      .map((item) => ({
        id: item.deck.id,
        kind: 'deck',
        storage: 'committed',
        path: outputName(item.deck),
        license: 'CC0-1.0',
        source: 'self-authored',
        producer: 'tools/corpus/gen',
        sha256: item.sha256,
        bytes: item.bytes.byteLength,
        slides: item.slides,
        zipEntries: item.entries,
        format: item.deck.extension ?? 'pptx',
        features: item.deck.features,
        description: item.deck.description,
        recipe: {
          tool: 'tools/corpus/tiers/a-generated/build-probes.ts',
          args: ['--out', 'corpus/decks', '--id', item.deck.id],
        },
        addedIn: item.deck.addedIn ?? '1.1',
      })),
  };
  const path = join(outDir, 'manifest.json');
  writeFileSync(path, JSON.stringify(manifest, null, 2) + '\n');
  // `JSON.stringify(..., null, 2)` puts every array element on its own line and
  // Prettier collapses the short ones, so what is written here is not what is
  // committed until Prettier has seen it. Said out loud because the failure is
  // otherwise `pnpm format:check` complaining about a file nobody edited.
  console.log('\nwrote ' + path + '\n  now run: npx prettier --write ' + path);
}
