/**
 * Turn the T8 fixture into the one table `@pptx-studio/text` cannot compute.
 *
 * ```
 * node tools/ground-truth/render/text/write-tables.ts
 * ```
 *
 * Everything else T8 measured is a rule the package implements and the tests
 * re-derive. Where an underline sits is not: it is a property of the typeface,
 * the browser will not tell us - `text-decoration` draws every face at the same
 * 0.05em, 0 of 16 - and reading the `post` table is sub-phase 8.1. So the cells
 * are data, and data that is measured gets generated rather than typed.
 *
 * The same shape as `tools/ground-truth/text/bullets/write-tables.ts`, and for
 * the same reason: a measured constant must not quietly become somebody's
 * memory of one.
 */

import { readFileSync, writeFileSync } from 'node:fs';

import { repoPath } from '../../../repo/root.ts';

interface FaceRule {
  readonly probe: string;
  readonly kind: 'u' | 's';
  readonly face: string;
  readonly size: number;
  readonly offsetEm: number;
  readonly thicknessEm: number;
}

interface Fixture {
  readonly powerpoint: { readonly decorationFace: readonly FaceRule[] };
}

const fixture = JSON.parse(
  readFileSync(repoPath('corpus/ground-truth/text-rendering.json'), 'utf8'),
) as unknown as Fixture;

const faces = new Map<string, { u?: FaceRule; s?: FaceRule }>();
for (const row of fixture.powerpoint.decorationFace) {
  const entry = faces.get(row.face) ?? {};
  if (entry[row.kind] !== undefined) {
    throw new Error(`${row.face} has two ${row.kind} rows in the fixture`);
  }
  entry[row.kind] = row;
  faces.set(row.face, entry);
}

const names = [...faces.keys()].sort((a, b) => a.localeCompare(b));
const rows = names.map((face) => {
  const entry = faces.get(face);
  if (entry?.u === undefined || entry.s === undefined) {
    throw new Error(`${face} was measured for only one kind of rule`);
  }
  return { face, u: entry.u, s: entry.s };
});

const cells = rows
  .map(
    ({ face, u, s }) =>
      `  ${JSON.stringify(face)}: {\n` +
      `    underline: { offset: ${String(u.offsetEm)}, thickness: ${String(u.thicknessEm)} },\n` +
      `    strike: { offset: ${String(s.offsetEm)}, thickness: ${String(s.thicknessEm)} },\n` +
      `  },`,
  )
  .join('\n');

const source = `/* Generated by tools/ground-truth/render/text/write-tables.ts. Do not edit. */

/** One rule, as fractions of the em: how far below the baseline, and how thick. */
export interface RuleMetrics {
  /** Below the baseline is positive, so a strikethrough's offset is negative. */
  readonly offset: number;
  readonly thickness: number;
}

/** The two rules a typeface carries. */
export interface FaceRules {
  readonly underline: RuleMetrics;
  readonly strike: RuleMetrics;
}

/**
 * Where PowerPoint drew each rule, measured at 120pt on a 1920-pixel export.
 *
 * ${String(rows.length)} face(s). Chromium's own \`text-decoration\` matches none of them.
 */
export const MEASURED_FACE_RULES: Readonly<Record<string, FaceRules>> = {
${cells}
};
`;

const out = repoPath('packages/text/src/runs/face-rules.gen.ts');
writeFileSync(out, source);
console.log(`${String(rows.length)} face(s) -> ${out}`);
