/**
 * The curve PowerPoint draws between two gradient stops - and the fact that it
 * only draws it sometimes.
 *
 * ## What is measured here
 *
 * A `a:gradFill` with **two distinct colours and a stop at each end** is not
 * interpolated linearly. A black-to-white ramp paints `BABABA` at its
 * midpoint, not `808080`. Anything else - three distinct colours, or two
 * colours whose stops do not reach 0 and 100% - is exactly linear in sRGB:
 * measured at worst 0.8 of a byte over 1920 samples, against 59 for the curve.
 *
 * Note "two colours", not "two stops". PowerPoint's own gallery writes variant 4
 * of every gradient style as three stops in two colours, and that *is* curved;
 * three stops in three colours at the same three positions is linear. See
 * `twoColorRamp` in `gradient.ts` for why, and for the mechanism that
 * predicts it.
 *
 * The blend space for the curved case is a plain 2.2 power, not the sRGB
 * piecewise transfer and not linear light. One weight curve, applied in that
 * space, reproduces five independently measured colour pairs - white to black,
 * two greys, red to green, blue to yellow, blue to red - to within one byte per
 * channel. That is what makes it a model rather than a table of one ramp.
 *
 * ## What is not known
 *
 * No closed form fits. A power law, a smoothstep, a logistic power and the sRGB
 * and linear-light transfers were all fitted over 1920 samples; the best is
 * eight bytes out at its worst. The plan predicted a "1.875 gamma ramp", and
 * `1 - (1 - t)^1.875` is indeed the closest single-parameter fit to the middle
 * of the range, but it misses the dark end by thirteen. So the curve ships as
 * what it is: measurement, not derivation.
 *
 * ## Why fifteen knots, and why they are not evenly spaced
 *
 * SVG interpolates between stops linearly in sRGB, and `color-interpolation`
 * does not apply to gradients in any shipping browser, so the only way to draw
 * this curve is to pre-sample it. Fifteen stops, adaptively placed, hold both
 * measured ramps - black to white and white to black, the two widest there are -
 * to within 1.9 of 255. Uniform spacing needs sixty-five to do worse, because
 * almost all the curvature is in the first twentieth of the ramp.
 *
 * The knots are fitted to **both** directions at once. A set fitted only to the
 * ascending ramp puts its knots where that ramp is steep and leaves the
 * descending ramp's steep end bare: ten such knots are within 1.2 bytes forwards
 * and thirteen backwards, which is a bug that only shows on gradients that run
 * light to dark.
 *
 * GENERATED by tools/ground-truth/write-paint-tables.ts from
 * corpus/ground-truth/fills.json. Do not edit: fill.test.ts re-derives it.
 */

/** The space the two-stop curve blends in: a plain 2.2 power, measured. */
export const RAMP_BLEND_GAMMA = 2.2;

/**
 * `[position, weight]` pairs, position and weight both 0 to 1.
 *
 * `weight` is the fraction of the *second* stop's colour, in the 2.2 power
 * space - so the colour at `position` is
 * `fromRampSpace(a + (b - a) * weight)` per channel, where `a` and `b` are
 * the two stop colours in that space.
 */
export const TWO_STOP_RAMP: readonly (readonly [number, number])[] = [
  [0.0, 0.000005],
  [0.004167, 0.001202],
  [0.016667, 0.00456],
  [0.054167, 0.016068],
  [0.177083, 0.078057],
  [0.289583, 0.183549],
  [0.43125, 0.383775],
  [0.545833, 0.579492],
  [0.652083, 0.740973],
  [0.7375, 0.845848],
  [0.822917, 0.921943],
  [0.935417, 0.980082],
  [0.983333, 0.99544],
  [0.995833, 0.998798],
  [1.0, 0.999995],
];

/** Into the blend space. */
export function toRampSpace(channel: number): number {
  return Math.pow(channel < 0 ? 0 : channel > 1 ? 1 : channel, RAMP_BLEND_GAMMA);
}

/** Out of the blend space. */
export function fromRampSpace(value: number): number {
  return Math.pow(value < 0 ? 0 : value > 1 ? 1 : value, 1 / RAMP_BLEND_GAMMA);
}

/**
 * The blend weight at `t`.
 *
 * Between two knots this interpolates in the **display** domain, not in the
 * weight domain, because that is what a viewer does with the stops we emit: SVG
 * and CSS both walk linearly from one stop's colour to the next. Interpolating
 * the weight instead is a different curve, and on the steep dark end of the ramp
 * it is nineteen bytes away from what PowerPoint paints; this way the worst
 * disagreement over the whole ramp is 1.6.
 *
 * So the ten knots are the model, and everything between them is defined to be
 * whatever a linear interpolation of the knot colours gives - which is the only
 * honest definition, since it is the only thing we can actually cause a browser
 * to draw.
 */
export function twoStopWeight(t: number): number {
  if (t <= 0) return TWO_STOP_RAMP[0]![1];
  const last = TWO_STOP_RAMP[TWO_STOP_RAMP.length - 1]!;
  if (t >= 1) return last[1];
  for (let i = 1; i < TWO_STOP_RAMP.length; i++) {
    const [pb, wb] = TWO_STOP_RAMP[i]!;
    if (t <= pb) {
      const [pa, wa] = TWO_STOP_RAMP[i - 1]!;
      if (pb === pa) return wb;
      const u = (t - pa) / (pb - pa);
      const da = fromRampSpace(wa);
      const db = fromRampSpace(wb);
      return toRampSpace(da + (db - da) * u);
    }
  }
  return last[1];
}
