/**
 * The 54 `ST_PresetPatternVal` tiles, measured out of PowerPoint's own export.
 *
 * ## Where these come from
 *
 * Not from Mono libgdiplus, which the plan proposed and which would have needed
 * a download. PowerPoint was asked to author one shape per `MsoPatternType`
 * through its object model; it accepted exactly 54 and spelled each name into
 * `a:pattFill/@prst` itself, so the enumeration below is PowerPoint's rather
 * than a transcription of anyone's. The pixels were then read back from a slide
 * export at 1280 x 720 - which over a 13.333 inch slide is exactly 96 DPI, the
 * one resolution at which the tile is 1:1 and its bits are not resampled.
 *
 * ## The tile is a physical size, not a shape fraction and not device pixels
 *
 * Eight pixels at 96 DPI: one twelfth of an inch, six points, 76200 EMU. The
 * same shape exported at 640, 1280, 1920 and 2560 pixels wide gives periods of
 * 4, 8, 12 and 16 pixels, so the tile scales with the *rendering resolution* and
 * not with the shape. In SVG that is `patternUnits="userSpaceOnUse"` with a
 * fixed size in slide units - never `objectBoundingBox`, which would stretch
 * the hatching of a wide shape into slanted mush.
 *
 * ## Coverage, not bits
 *
 * Fifty-one of the 54 are one-bit. `dnDiag`, `upDiag` and `diagCross` are
 * drawn as antialiased diagonal lines and their tiles contain intermediate
 * values, so every tile is stored as coverage. `lgGrid` and `cross` measure
 * byte-identical, which is the only such pair among the 54 and matches the GDI+
 * heritage where `LargeGrid` is an alias of `Cross`.
 *
 * The `pctNN` names are labels rather than measurements: `pct75` covers 88%
 * of its tile and `pct20` covers 13%.
 *
 * GENERATED by tools/ground-truth/paint/fills/write-tables.ts from
 * corpus/ground-truth/fills.json. Do not edit: fill.test.ts re-derives it.
 */

/** One tile, at its minimal repeating period. */
export interface PatternTile {
  /** Width of the repeat, in pixels at 96 DPI. */
  readonly w: number;
  /** Height of the repeat, in pixels at 96 DPI. */
  readonly h: number;
  /**
   * Row-major coverage, two hex digits per pixel: `00` is the background
   * colour, `FF` the foreground, and anything between is antialiasing.
   */
  readonly cover: string;
}

/** One tile pixel, in EMU. 914400 / 96. */
export const PATTERN_PIXEL_EMU = 9525;

/** The full tile is always eight of those square, whatever the minimal period is. */
export const PATTERN_TILE_PIXELS = 8;

export const PATTERN_TILES: Readonly<Record<string, PatternTile>> = {
  pct5: {
    w: 8,
    h: 8,
    cover:
      '0000FF0000000000000000000000000000000000000000000000000000000000000000000000FF00000000000000000000000000000000000000000000000000',
  },
  pct10: { w: 8, h: 4, cover: '000000000000FF0000000000000000000000FF00000000000000000000000000' },
  pct20: { w: 4, h: 4, cover: '0000FF0000000000FF00000000000000' },
  pct25: { w: 4, h: 2, cover: '0000FF00FF000000' },
  pct30: { w: 4, h: 4, cover: 'FF00FF00000000FFFF00FF0000FF0000' },
  pct40: {
    w: 8,
    h: 8,
    cover:
      'FF00FF00FF00FF0000FF00FF00FF00FFFF00FF00FF00FF0000FF000000FF00FFFF00FF00FF00FF0000FF00FF00FF00FFFF00FF00FF00FF0000FF00FF00FF0000',
  },
  pct50: { w: 2, h: 2, cover: 'FF0000FF' },
  pct60: { w: 4, h: 4, cover: 'FF00FFFF00FF00FFFFFFFF0000FF00FF' },
  pct70: { w: 4, h: 2, cover: 'FFFF00FF00FFFFFF' },
  pct75: { w: 4, h: 4, cover: 'FFFF00FFFFFFFFFF00FFFFFFFFFFFFFF' },
  pct80: { w: 8, h: 4, cover: 'FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFF' },
  pct90: {
    w: 8,
    h: 8,
    cover:
      'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFF',
  },
  dkHorz: { w: 1, h: 4, cover: 'FFFF0000' },
  dkVert: { w: 4, h: 1, cover: '0000FFFF' },
  dkDnDiag: { w: 4, h: 4, cover: '0000FFFFFF0000FFFFFF000000FFFF00' },
  dkUpDiag: { w: 4, h: 4, cover: 'FFFF0000FF0000FF0000FFFF00FFFF00' },
  smCheck: { w: 4, h: 4, cover: '00FFFF00FF0000FFFF0000FF00FFFF00' },
  trellis: { w: 4, h: 4, cover: 'FFFFFFFFFF0000FFFFFFFFFF00FFFF00' },
  ltHorz: { w: 1, h: 4, cover: 'FF000000' },
  ltVert: { w: 4, h: 1, cover: '0000FF00' },
  ltDnDiag: { w: 4, h: 4, cover: '0000FF00000000FFFF00000000FF0000' },
  ltUpDiag: { w: 4, h: 4, cover: '00FF0000FF000000000000FF0000FF00' },
  smGrid: { w: 4, h: 4, cover: 'FFFFFFFF0000FF000000FF000000FF00' },
  dotDmnd: {
    w: 8,
    h: 8,
    cover:
      '0000FF00000000000000000000000000FF000000FF0000000000000000000000000000000000FF000000000000000000FF000000FF0000000000000000000000',
  },
  wdDnDiag: {
    w: 8,
    h: 8,
    cover:
      '00FFFFFF000000000000FFFFFF000000000000FFFFFF000000000000FFFFFF000000000000FFFFFFFF0000000000FFFFFFFF0000000000FFFFFFFF0000000000',
  },
  wdUpDiag: {
    w: 8,
    h: 8,
    cover:
      '00000000FFFFFF00000000FFFFFF00000000FFFFFF00000000FFFFFF00000000FFFFFF0000000000FFFF0000000000FFFF0000000000FFFF0000000000FFFFFF',
  },
  dashUpDiag: {
    w: 4,
    h: 8,
    cover: '000000000000000000FF0000FF000000000000FF0000FF000000000000000000',
  },
  dashDnDiag: {
    w: 4,
    h: 8,
    cover: '00000000000000000000FF00000000FFFF00000000FF00000000000000000000',
  },
  narVert: { w: 2, h: 1, cover: '00FF' },
  narHorz: { w: 1, h: 2, cover: 'FF00' },
  dashVert: {
    w: 8,
    h: 8,
    cover:
      '0000FF00000000000000FF00000000000000FF00000000000000FF0000000000000000000000FF00000000000000FF00000000000000FF00000000000000FF00',
  },
  dashHorz: {
    w: 8,
    h: 8,
    cover:
      '0000FFFFFFFF0000000000000000000000000000000000000000000000000000FFFF00000000FFFF000000000000000000000000000000000000000000000000',
  },
  lgConfetti: {
    w: 8,
    h: 8,
    cover:
      '00FFFF000000FFFF000000000000FFFF0000FFFF000000000000FFFF00FFFF00FFFF000000FFFF00FFFF00000000000000000000FFFF000000FFFF00FFFF0000',
  },
  lgGrid: {
    w: 8,
    h: 8,
    cover:
      '000000000000FF00000000000000FF00000000000000FF00000000000000FF00FFFFFFFFFFFFFFFF000000000000FF00000000000000FF00000000000000FF00',
  },
  horzBrick: {
    w: 8,
    h: 8,
    cover:
      'FFFFFFFFFFFFFFFF0000FF00000000000000FF00000000000000FF0000000000FFFFFFFFFFFFFFFF000000000000FF00000000000000FF00000000000000FF00',
  },
  lgCheck: {
    w: 8,
    h: 8,
    cover:
      'FFFF00000000FFFFFFFF00000000FFFFFFFF00000000FFFFFFFF00000000FFFF0000FFFFFFFF00000000FFFFFFFF00000000FFFFFFFF00000000FFFFFFFF0000',
  },
  smConfetti: {
    w: 8,
    h: 8,
    cover:
      '000000000000FF000000FF000000000000000000000000FF00000000FF00000000FF0000000000000000000000FF0000FF00000000000000000000FF00000000',
  },
  zigZag: { w: 8, h: 4, cover: '0000000000FFFF0000000000FF0000FFFF0000FF0000000000FFFF0000000000' },
  solidDmnd: {
    w: 8,
    h: 8,
    cover:
      '00FF000000000000FFFFFF0000000000FFFFFFFF000000FFFFFFFFFFFF00FFFFFFFFFFFF000000FFFFFFFF000000000000FF0000000000000000000000000000',
  },
  diagBrick: {
    w: 8,
    h: 8,
    cover:
      '0000000000FF000000000000FF000000000000FF000000000000FF000000000000FFFF0000000000FF0000FF0000000000000000FF0000FF0000000000FFFF00',
  },
  openDmnd: {
    w: 8,
    h: 8,
    cover:
      'FF00FF0000000000000000FF000000FF00000000FF00FF000000000000FF000000000000FF00FF00000000FF000000FFFF00FF000000000000FF000000000000',
  },
  plaid: {
    w: 8,
    h: 8,
    cover:
      'FFFF00000000FFFFFFFF00000000FFFFFFFF00000000FFFFFFFF00000000FFFFFF00FF00FF00FF0000FF00FF00FF00FFFF00FF00FF00FF0000FF00FF00FF00FF',
  },
  sphere: {
    w: 8,
    h: 8,
    cover:
      'FFFF00FFFFFF00FF00FFFF000000FF00FFFFFF000000FFFFFFFFFF000000FFFFFFFF00FFFFFF00FF0000FF0000FFFF000000FFFFFFFFFF000000FFFFFFFFFF00',
  },
  weave: {
    w: 8,
    h: 8,
    cover:
      '0000FF000000FF0000FF00FF00000000FF000000FF00000000FF000000FF00FF0000FF000000FF0000FF00FF000000FFFF000000FF000000000000FF00FF00FF',
  },
  dotGrid: {
    w: 8,
    h: 8,
    cover:
      '000000000000FF000000000000000000000000000000FF000000000000000000FF00FF00FF00FF000000000000000000000000000000FF000000000000000000',
  },
  divot: {
    w: 8,
    h: 8,
    cover:
      '000000000000000000FF0000000000000000FF000000000000FF0000000000000000000000000000000000000000FF000000000000FF0000000000000000FF00',
  },
  shingle: {
    w: 8,
    h: 8,
    cover:
      '00000000FFFF0000000000FF0000FF000000FF00000000FFFFFF0000000000000000FFFF0000000000000000FF0000000000000000FF00000000000000FF0000',
  },
  wave: { w: 8, h: 4, cover: '000000000000000000FFFF0000000000FF0000FF00FF0000000000000000FFFF' },
  horz: { w: 1, h: 8, cover: 'FF00000000000000' },
  vert: { w: 8, h: 1, cover: '000000000000FF00' },
  cross: {
    w: 8,
    h: 8,
    cover:
      '000000000000FF00000000000000FF00000000000000FF00000000000000FF00FFFFFFFFFFFFFFFF000000000000FF00000000000000FF00000000000000FF00',
  },
  dnDiag: {
    w: 8,
    h: 8,
    cover:
      '0046FF4600000000000046FF4600000000000046FF4600000000000046FF4600000000000046FF4646000000000046FFFF4600000000004646FF460000000000',
  },
  upDiag: {
    w: 8,
    h: 8,
    cover:
      '46FF460000000000FF4600000000004646000000000046FF000000000046FF460000000046FF460000000046FF460000000046FF460000000046FF4600000000',
  },
  diagCross: {
    w: 8,
    h: 8,
    cover:
      '46FFFF4600000000FF4646FF4600004646000046FF4646FF0000000046FFFF460000000046FFFF4646000046FF4646FFFF4646FF4600004646FFFF4600000000',
  },
};

/** The 54 names, in `MsoPatternType` order - the order PowerPoint enumerated them. */
export const PRESET_PATTERN_NAMES: readonly string[] = [
  'pct5',
  'pct10',
  'pct20',
  'pct25',
  'pct30',
  'pct40',
  'pct50',
  'pct60',
  'pct70',
  'pct75',
  'pct80',
  'pct90',
  'dkHorz',
  'dkVert',
  'dkDnDiag',
  'dkUpDiag',
  'smCheck',
  'trellis',
  'ltHorz',
  'ltVert',
  'ltDnDiag',
  'ltUpDiag',
  'smGrid',
  'dotDmnd',
  'wdDnDiag',
  'wdUpDiag',
  'dashUpDiag',
  'dashDnDiag',
  'narVert',
  'narHorz',
  'dashVert',
  'dashHorz',
  'lgConfetti',
  'lgGrid',
  'horzBrick',
  'lgCheck',
  'smConfetti',
  'zigZag',
  'solidDmnd',
  'diagBrick',
  'openDmnd',
  'plaid',
  'sphere',
  'weave',
  'dotGrid',
  'divot',
  'shingle',
  'wave',
  'horz',
  'vert',
  'cross',
  'dnDiag',
  'upDiag',
  'diagCross',
];

/** The three tiles PowerPoint antialiases rather than drawing one-bit. */
export const ANTIALIASED_PATTERNS: readonly string[] = ['dnDiag', 'upDiag', 'diagCross'];

/**
 * Is this one of the 54?
 *
 * Deliberately a plain boolean and not a type predicate: `PATTERN_TILES` is
 * keyed by `string`, so a predicate would narrow the *failing* branch to
 * `never` and make the error path unwritable.
 */
export function isPresetPatternName(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(PATTERN_TILES, name);
}
