/**
 * Experiment T10, step 1 - write the probe deck.
 *
 * ```
 * node tools/ground-truth/text/vertical-glyphs/build-deck.ts <work-dir>
 * ```
 *
 * One package, `vertical-glyphs.pptx`, plus `glyph-inputs.json` naming every
 * probe's slide and rectangle so the reader and the analysis agree about which
 * ink belongs to which probe.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  allProbes,
  FRAME_PT,
  RASTER_PER_SLIDE,
  SLIDE_PT,
  STREAM_PER_SLIDE,
  type Probe,
} from './probes.ts';
import { buildSheetPackage, SCHEME_ONE, shape, type Rect } from '../../lib/sheet-pptx.ts';

const arg = process.argv[2];
if (arg === undefined) throw new Error('usage: build-deck.ts <out-dir>');
const outDir: string = arg;
mkdirSync(outDir, { recursive: true });

function escapeXml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** Black text on a frame with no fill and no line: the only ink is the glyph. */
function paragraphs(probe: Probe): readonly string[] {
  const rPr =
    `<a:rPr lang="ja-JP" sz="${String(Math.round(probe.sizePt * 100))}">` +
    '<a:solidFill><a:srgbClr val="000000"/></a:solidFill>' +
    `<a:latin typeface="${probe.face}"/><a:ea typeface="${probe.face}"/></a:rPr>`;
  const one = `<a:p><a:pPr algn="l"/><a:r>${rPr}<a:t>${escapeXml(probe.text)}</a:t></a:r></a:p>`;
  // The pitch family is the one that needs a second line, and it has to be a
  // second paragraph: a wrap would make the reading depend on the break model.
  return probe.family === 'pitch' ? [one, one] : [one];
}

/** Which slide each probe sits on, and where, with raster probes packed first. */
function place(probes: readonly Probe[]): readonly { probe: Probe; slide: number; rect: Rect }[] {
  const out: { probe: Probe; slide: number; rect: Rect }[] = [];
  const raster = probes.filter((row) => row.raster);
  const stream = probes.filter((row) => !row.raster);
  let slide = 0;

  const pack = (rows: readonly Probe[], perSlide: number, columns: number): void => {
    for (let at = 0; at < rows.length; at += perSlide) {
      slide += 1;
      rows.slice(at, at + perSlide).forEach((probe, index) => {
        const column = index % columns;
        const row = Math.floor(index / columns);
        out.push({
          probe,
          slide,
          rect: {
            x: column * (SLIDE_PT.widthPt / columns) + 4,
            y: row * (SLIDE_PT.heightPt / Math.ceil(perSlide / columns)) + 4,
            w: FRAME_PT.widthPt,
            h: FRAME_PT.heightPt,
          },
        });
      });
    }
  };

  pack(raster, RASTER_PER_SLIDE, 3);
  pack(stream, STREAM_PER_SLIDE, 4);
  return out;
}

const placed = place(allProbes());
const slides = Math.max(...placed.map((row) => row.slide));

const spec = {
  themes: [{ scheme: SCHEME_ONE }],
  masters: [{ theme: 0 }],
  layouts: [{ master: 0 }],
  slides: Array.from({ length: slides }, (_, index) => ({
    layout: 0,
    shapes: placed
      .filter((row) => row.slide === index + 1)
      .map((row, at) =>
        shape({
          id: 10 + at,
          name: row.probe.id,
          rect: row.rect,
          fill: '<a:noFill/>',
          bodyPr:
            `<a:bodyPr vert="${row.probe.vert}" wrap="none" anchor="t"` +
            ' lIns="0" tIns="0" rIns="0" bIns="0"/>',
          paragraphs: paragraphs(row.probe),
        }),
      ),
  })),
};

writeFileSync(join(outDir, 'vertical-glyphs.pptx'), buildSheetPackage(spec));
writeFileSync(
  join(outDir, 'glyph-inputs.json'),
  JSON.stringify(
    {
      $comment: 'GENERATED by tools/ground-truth/text/vertical-glyphs/build-deck.ts',
      slidePt: SLIDE_PT,
      framePt: FRAME_PT,
      probes: placed.map((row) => ({ ...row.probe, slide: row.slide, rect: row.rect })),
    },
    null,
    2,
  ),
);

process.stdout.write(
  `vertical-glyphs.pptx: ${String(placed.length)} probe(s) on ${String(slides)} slide(s), ` +
    `${String(placed.filter((row) => row.probe.raster).length)} rastered\n`,
);
