/**
 * Experiment T10, step 2b - ask Chromium the metric the renderer will actually
 * have.
 *
 * ```
 * node tools/ground-truth/text/vertical-glyphs/measure-in-browser.ts <work-dir>
 * ```
 *
 * PowerPoint's answer is the reference; this is what ships. An upright glyph's
 * baseline sits one less the ideographic baseline down its cell, and
 * `TextMetrics.ideographicBaseline` is the only route to that number in a
 * browser - so whether it agrees with what PowerPoint drew is the honest ceiling
 * on vertical East Asian fidelity, and this is where the number comes from.
 *
 * The same `OffscreenCanvas` the Worker measures on, not a DOM `<canvas>`.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { chromium } from 'playwright';

import { FACES, BAR } from './probes.ts';

/*
 * `page.evaluate` runs in Chromium and `tools/` is compiled with no DOM library,
 * so the surface this file uses is declared rather than imported - narrow enough
 * that a body which reaches for anything else fails to compile.
 */
interface BrowserMetrics {
  readonly width: number;
  readonly fontBoundingBoxAscent: number;
  readonly fontBoundingBoxDescent: number;
  readonly ideographicBaseline: number;
}
interface BrowserCtx {
  font: string;
  letterSpacing: string;
  fontKerning: string;
  measureText(text: string): BrowserMetrics;
}
interface BrowserCanvas {
  getContext(id: '2d'): BrowserCtx | null;
}

const arg = process.argv[2];
if (arg === undefined) throw new Error('usage: measure-in-browser.ts <work-dir>');
const work: string = arg;

/** The size the face box is read at, matching `FACE_BOX_PX` in the package. */
const AT_PX = 1000;

const browser = await chromium.launch();
try {
  const page = await browser.newPage();
  const faces = await page.evaluate(
    ({ names, at, bar }: { names: readonly string[]; at: number; bar: string }) => {
      const make = (
        globalThis as unknown as { OffscreenCanvas: new (w: number, h: number) => BrowserCanvas }
      ).OffscreenCanvas;
      const ctx = new make(1, 1).getContext('2d');
      if (ctx === null) throw new Error('no 2d context');
      return names.map((name) => {
        ctx.font = `${String(at)}px "${name}"`;
        ctx.letterSpacing = '0px';
        ctx.fontKerning = 'normal';
        const box = ctx.measureText('Hxg');
        const ideograph = ctx.measureText(bar);
        return {
          face: name,
          ascent: box.fontBoundingBoxAscent / at,
          descent: box.fontBoundingBoxDescent / at,
          ideographic: -ideograph.ideographicBaseline / at,
          advance: ideograph.width / at,
        };
      });
    },
    { names: FACES, at: AT_PX, bar: BAR },
  );

  const userAgent = await page.evaluate(() => navigator.userAgent);
  writeFileSync(
    join(work, 'glyph-browser.json'),
    `${JSON.stringify(
      {
        $comment: 'GENERATED by tools/ground-truth/text/vertical-glyphs/measure-in-browser.ts',
        atPx: AT_PX,
        userAgent,
        faces,
      },
      null,
      2,
    )}\n`,
  );
  process.stdout.write(`glyph-browser.json: ${String(faces.length)} face(s)\n`);
  for (const face of faces) {
    process.stdout.write(
      `  ${face.face.padEnd(18)} ideographic ${face.ideographic.toFixed(4)}  ` +
        `so an upright baseline at ${(1 - face.ideographic).toFixed(4)} of the em\n`,
    );
  }
} finally {
  await browser.close();
}
