/**
 * The eleven preset dash arrays, in multiples of the stroke width.
 *
 * GENERATED by tools/ground-truth/paint/lines/write-tables.ts from
 * corpus/ground-truth/lines.json. Do not edit by hand.
 *
 * Measured, not transcribed. Each preset was drawn as a 920pt line at 12pt wide,
 * exported at four pixels to the point, and the on and off lengths recovered
 * from where coverage crosses one half - which locates an edge to about a tenth
 * of a pixel, so a segment of four stroke widths is measured to better than half
 * a percent. Every one of the 34 numbers below came out within 0.02 of a whole
 * number, at three different stroke widths.
 *
 * The arrays that circulate for these presets are, for once, exactly right: all
 * ten non-solid presets were also written as an explicit `a:custDash` of the
 * quoted array in the same experiment, and all ten painted an identical row.
 *
 * The unit is deliberate and not a convenience. `a:custDash/a:ds/@d` is a
 * percentage *of the line width*, so a width multiple is the only form in which
 * a dash can be written back into a file at all.
 */

/** One dash and the gap that follows it, both in multiples of the stroke width. */
export interface DashSegment {
  readonly d: number;
  readonly sp: number;
}

export const PRESET_DASHES: Readonly<Record<string, readonly DashSegment[]>> = {
  solid: [],
  dot: [{ d: 1, sp: 3 }],
  sysDot: [{ d: 1, sp: 1 }],
  dash: [{ d: 4, sp: 3 }],
  sysDash: [{ d: 3, sp: 1 }],
  lgDash: [{ d: 8, sp: 3 }],
  dashDot: [
    { d: 4, sp: 3 },
    { d: 1, sp: 3 },
  ],
  sysDashDot: [
    { d: 3, sp: 1 },
    { d: 1, sp: 1 },
  ],
  lgDashDot: [
    { d: 8, sp: 3 },
    { d: 1, sp: 3 },
  ],
  lgDashDotDot: [
    { d: 8, sp: 3 },
    { d: 1, sp: 3 },
    { d: 1, sp: 3 },
  ],
  sysDashDotDot: [
    { d: 3, sp: 1 },
    { d: 1, sp: 1 },
    { d: 1, sp: 1 },
  ],
};

/** The eleven `ST_PresetLineDashVal` names, as PowerPoint spelled them itself. */
export const PRESET_DASH_NAMES: readonly string[] = [
  'solid',
  'dot',
  'sysDot',
  'dash',
  'sysDash',
  'lgDash',
  'dashDot',
  'sysDashDot',
  'lgDashDot',
  'lgDashDotDot',
  'sysDashDotDot',
];

/**
 * Deliberately not a type predicate.
 *
 * `PRESET_DASHES` is keyed by `string`, so narrowing here would narrow the
 * failing branch to `never` and the error path could not name what it rejected.
 */
export function isPresetDashName(name: string): boolean {
  return Object.hasOwn(PRESET_DASHES, name);
}
