/**
 * The six `ST_LineEndType` markers and the three sizes each takes.
 *
 * GENERATED by tools/ground-truth/paint/lines/write-tables.ts from
 * corpus/ground-truth/lines.json. Do not edit by hand.
 *
 * Measured, and deliberately so. The obvious source for arrowhead geometry is
 * LibreOffice's vertex tables, which are MPL-2.0 - a file-level copyleft this
 * Apache-2.0 tree cannot take. So every head was drawn at 8pt, exported at
 * four pixels to the point, and recovered as a per-column ink profile around the
 * line's endpoint. That profile is the silhouette, sampled; fitting the three
 * outline families to it gives the extent that no threshold can, because an
 * ellipse's silhouette reaches the shaft's own height well inside its back edge
 * and thresholding one reports every oval about nine percent short.
 *
 * What came out:
 *
 *   - Three sizes, and the same three for both `@len` and `@w`:
 *     sm = 2, med = 3, lg = 5 stroke widths. Confirmed on all 54
 *     combinations, and at stroke widths of 4, 8 and 16 points.
 *   - A triangle and a stealth share a silhouette. Only how much of it is inked
 *     tells them apart, and the stealth's notch is a quarter of its length.
 *   - A diamond and an oval are **centred on the line's endpoint**. The other
 *     three put their tip there. Getting this wrong moves a large head by half
 *     its length.
 *   - An open arrow is a stroked V rather than a filled outline, which is why
 *     its silhouette measures wider than its nominal width.
 */

/** Which end of the marker sits on the line's own endpoint. */
export type MarkerAnchor = 'tip' | 'centre';

export interface Marker {
  /** The family the silhouette was fitted to. */
  readonly outline: string;
  readonly anchor: MarkerAnchor;
  /** False for `arrow`, which is stroked rather than filled. */
  readonly filled: boolean;
  /** How far the back is cut forward, as a fraction of the length. Zero for most. */
  readonly notch: number;
  /**
   * The outline in a unit box: x from 0 at the back to 1 at the tip, y from
   * -0.5 to 0.5. Scale by (len x w, wid x w) to get the marker at a stroke
   * width of w.
   */
  readonly path: string;
}

/** `@len` and `@w`, in multiples of the stroke width. */
export const MARKER_SIZE: Readonly<Record<string, number>> = {
  sm: 2,
  med: 3,
  lg: 5,
};

export const MARKER_SIZE_NAMES: readonly string[] = ['sm', 'med', 'lg'];

export const MARKERS: Readonly<Record<string, Marker>> = {
  none: {
    outline: 'none',
    anchor: 'tip',
    filled: false,
    notch: 0,
    path: '',
  },
  triangle: {
    outline: 'triangle',
    anchor: 'tip',
    filled: true,
    notch: 0,
    path: 'M0,-0.5 L1,0 L0,0.5 Z',
  },
  stealth: {
    outline: 'triangle',
    anchor: 'tip',
    filled: true,
    notch: 0.25,
    path: 'M0,-0.5 L1,0 L0,0.5 L0.25,0 Z',
  },
  diamond: {
    outline: 'diamond',
    anchor: 'centre',
    filled: true,
    notch: 0,
    path: 'M0,0 L0.5,-0.5 L1,0 L0.5,0.5 Z',
  },
  oval: {
    outline: 'ellipse',
    anchor: 'centre',
    filled: true,
    notch: 0,
    path: 'M0,0 A0.5,0.5 0 0 1 1,0 A0.5,0.5 0 0 1 0,0 Z',
  },
  arrow: {
    outline: 'triangle',
    anchor: 'tip',
    filled: false,
    notch: 0.34,
    path: 'M0,-0.5 L1,0 L0,0.5',
  },
};

export const MARKER_TYPE_NAMES: readonly string[] = [
  'none',
  'triangle',
  'stealth',
  'diamond',
  'oval',
  'arrow',
];

/** Deliberately not a type predicate; see `isPresetDashName` for why. */
export function isMarkerTypeName(name: string): boolean {
  return Object.hasOwn(MARKERS, name);
}

/** Deliberately not a type predicate. */
export function isMarkerSizeName(name: string): boolean {
  return Object.hasOwn(MARKER_SIZE, name);
}
