/**
 * Turn the T1 fixture into the one table `@pptx-studio/model` ships.
 *
 * ```
 * node tools/ground-truth/text/cascade/write-tables.ts
 * ```
 *
 * Writes `packages/model/src/builtin-text-styles.ts` from
 * `corpus/ground-truth/text-cascade.json`. The table is not hand-written and may
 * not be hand-edited: `text.test.ts` re-derives it from the same fixture and
 * fails if the two have drifted, which is the only thing standing between a
 * measured constant and somebody's memory of one.
 */

import { readFileSync, writeFileSync } from 'node:fs';

interface BuiltinLevel {
  level: number;
  szHundredths: number;
  marLEmu: number;
  indentEmu: number;
  bullet: boolean;
}

interface Fixture {
  model: {
    floor: { szHundredths: number; marLEmu: number; indentEmu: number };
    builtinTextStyles: {
      title: BuiltinLevel[];
      body: BuiltinLevel[];
      other: BuiltinLevel[];
    };
  };
}

const fixture = JSON.parse(
  readFileSync('corpus/ground-truth/text-cascade.json', 'utf8'),
) as Fixture;

const { floor, builtinTextStyles } = fixture.model;

function bucket(name: 'title' | 'body' | 'other'): string {
  const levels = builtinTextStyles[name];
  if (levels.length !== 9) throw new Error(`${name} has ${String(levels.length)} levels, not 9`);
  const rows = levels
    .map(
      (l) =>
        `    { sz: ${String(l.szHundredths)}, marL: ${String(l.marLEmu)}, ` +
        `indent: ${String(l.indentEmu)}, bullet: ${String(l.bullet)} },`,
    )
    .join('\n');
  return `  ${name}: [\n${rows}\n  ],`;
}

const source = `/**
 * PowerPoint's own \`p:txStyles\`, substituted when a master declares none.
 *
 * GENERATED by tools/ground-truth/text/cascade/write-tables.ts from
 * corpus/ground-truth/text-cascade.json. Do not edit by hand.
 *
 * Measured, not transcribed. Nine paragraphs at \`lvl="0"\` through \`lvl="8"\` in a
 * title placeholder, a body placeholder and a shape that is not a placeholder,
 * in a package whose master carries no \`p:txStyles\` at all, read back through
 * PowerPoint's own object model. The body ladder - 28, 24, 20 and then 18 for
 * the rest - is not a number anything in the file declares, which is how the
 * ladder experiment discovered there was a source below every source the plan
 * names.
 *
 * A PowerPoint-authored master always writes \`p:txStyles\`, so this table only
 * ever applies to a hand-written or damaged one. It exists because the
 * alternative is a placeholder resolving to no size at all, and because a
 * measured answer costs one deck.
 *
 * Only the three properties 3.1 resolves are recorded. \`bullet\` says whether
 * PowerPoint drew one, which is what 3.5 will need to reproduce; the glyph and
 * its font belong to that sub-phase and are in the fixture, not here.
 */

/** One level of a built-in list style. */
export interface BuiltinLevel {
  /** Hundredths of a point, as \`a:defRPr/@sz\` holds it. */
  readonly sz: number;
  /** EMU, as \`a:lvlNpPr/@marL\` holds it. */
  readonly marL: number;
  /** EMU, as \`a:lvlNpPr/@indent\` holds it. Negative is a hanging indent. */
  readonly indent: number;
  readonly bullet: boolean;
}

/** The three buckets, nine levels each, level 1 first. */
export const BUILTIN_TEXT_STYLES: {
  readonly title: readonly BuiltinLevel[];
  readonly body: readonly BuiltinLevel[];
  readonly other: readonly BuiltinLevel[];
} = {
${bucket('title')}
${bucket('body')}
${bucket('other')}
};

/**
 * What is left when every source is silent and the master *does* declare
 * \`p:txStyles\`.
 *
 * Distinct from the table above, and measured separately: a body placeholder
 * whose \`p:bodyStyle/a:lvl1pPr\` declares only a \`marL\` came back at
 * ${String(floor.szHundredths / 100)} points rather than the built-in body style's
 * ${String((builtinTextStyles.body[0]?.szHundredths ?? 0) / 100)}, and with no indent rather than the built-in's
 * hanging one. So the built-in styles are substituted wholesale for an absent
 * \`p:txStyles\` and are not a per-property backstop underneath a present one.
 *
 * \`marL\` and \`indent\` are **0**, not the ECMA-376 schema defaults of 347663 and
 * -342900. Materialising those at parse time gives every paragraph a
 * 27-point hanging indent nothing asked for, and blocks the inherited value on
 * top of it, because a default that has been written down cannot be told from a
 * declaration.
 */
export const TEXT_FLOOR: BuiltinLevel = {
  sz: ${String(floor.szHundredths)},
  marL: ${String(floor.marLEmu)},
  indent: ${String(floor.indentEmu)},
  bullet: false,
};
`;

writeFileSync('packages/model/src/builtin-text-styles.ts', source);
console.log('wrote packages/model/src/builtin-text-styles.ts');
