/* eslint-disable */
// Generated by tools/geometry-codegen/generate.ts. Do not edit.
//
// Provenance, totals, and the two things in the source that ECMA does not describe.
//
// Source: Apache POI's presetShapeDefinitions.xml, Apache-2.0, Copyright The
// Apache Software Foundation. The file itself is not redistributed here; these
// are the shape definitions transcoded out of it. See NOTICE.
//
//   presetShapeDefinitions.xml   538970 bytes
//   sha256 4a762444d8d85876881c02a5b1dedf6f73006fcd8acb7b4e393435615b37c780
//
// Encoding: see packages/geometry/src/decode.ts, which is the only reader.

export const PRESET_SOURCE = {
  file: "presetShapeDefinitions.xml",
  sha256: "4a762444d8d85876881c02a5b1dedf6f73006fcd8acb7b4e393435615b37c780",
  bytes: 538970,
  root: "presetShapeDefinitons",
} as const;

/** Counted on the generator side, from the parse. The suite checks the decode against these. */
export const PRESET_TOTALS = {
  "shapes": 187,
  "avGuides": 300,
  "gdGuides": 3622,
  "handles": 243,
  "sites": 860,
  "textRects": 182,
  "paths": 320,
  "commands": 2915
} as const;

export const BUCKET_MEMBERS = {
  "basic": [
    "arc",
    "bevel",
    "blockArc",
    "bracePair",
    "bracketPair",
    "can",
    "chord",
    "cloud",
    "corner",
    "cube",
    "decagon",
    "diagStripe",
    "diamond",
    "dodecagon",
    "donut",
    "ellipse",
    "foldedCorner",
    "frame",
    "halfFrame",
    "heart",
    "heptagon",
    "hexagon",
    "leftBrace",
    "leftBracket",
    "lightningBolt",
    "moon",
    "noSmoking",
    "octagon",
    "parallelogram",
    "pentagon",
    "pie",
    "plaque",
    "plus",
    "rect",
    "rightBrace",
    "rightBracket",
    "roundRect",
    "rtTriangle",
    "smileyFace",
    "sun",
    "teardrop",
    "trapezoid",
    "triangle"
  ],
  "arrows": [
    "bentArrow",
    "bentUpArrow",
    "chevron",
    "circularArrow",
    "curvedDownArrow",
    "curvedLeftArrow",
    "curvedRightArrow",
    "curvedUpArrow",
    "downArrow",
    "downArrowCallout",
    "homePlate",
    "leftArrow",
    "leftArrowCallout",
    "leftCircularArrow",
    "leftRightArrow",
    "leftRightArrowCallout",
    "leftRightCircularArrow",
    "leftRightUpArrow",
    "leftUpArrow",
    "notchedRightArrow",
    "quadArrow",
    "quadArrowCallout",
    "rightArrow",
    "rightArrowCallout",
    "stripedRightArrow",
    "swooshArrow",
    "upArrowCallout",
    "upDownArrow",
    "upArrow",
    "upDownArrowCallout",
    "uturnArrow"
  ],
  "callouts": [
    "accentBorderCallout1",
    "accentBorderCallout2",
    "accentBorderCallout3",
    "accentCallout1",
    "accentCallout2",
    "accentCallout3",
    "borderCallout1",
    "borderCallout2",
    "borderCallout3",
    "callout1",
    "callout2",
    "callout3",
    "cloudCallout",
    "wedgeEllipseCallout",
    "wedgeRectCallout",
    "wedgeRoundRectCallout"
  ],
  "flowchart": [
    "flowChartAlternateProcess",
    "flowChartCollate",
    "flowChartConnector",
    "flowChartDecision",
    "flowChartDelay",
    "flowChartDisplay",
    "flowChartDocument",
    "flowChartExtract",
    "flowChartInputOutput",
    "flowChartInternalStorage",
    "flowChartMagneticDisk",
    "flowChartMagneticDrum",
    "flowChartMagneticTape",
    "flowChartManualInput",
    "flowChartManualOperation",
    "flowChartMerge",
    "flowChartMultidocument",
    "flowChartOfflineStorage",
    "flowChartOffpageConnector",
    "flowChartOnlineStorage",
    "flowChartOr",
    "flowChartPredefinedProcess",
    "flowChartPreparation",
    "flowChartProcess",
    "flowChartPunchedCard",
    "flowChartPunchedTape",
    "flowChartSort",
    "flowChartSummingJunction",
    "flowChartTerminator"
  ],
  "misc": [
    "actionButtonBackPrevious",
    "actionButtonBeginning",
    "actionButtonBlank",
    "actionButtonDocument",
    "actionButtonEnd",
    "actionButtonForwardNext",
    "actionButtonHelp",
    "actionButtonHome",
    "actionButtonInformation",
    "actionButtonMovie",
    "actionButtonReturn",
    "actionButtonSound",
    "bentConnector2",
    "bentConnector3",
    "bentConnector4",
    "bentConnector5",
    "chartPlus",
    "chartStar",
    "chartX",
    "cornerTabs",
    "curvedConnector2",
    "curvedConnector3",
    "curvedConnector4",
    "curvedConnector5",
    "funnel",
    "gear6",
    "gear9",
    "line",
    "lineInv",
    "mathDivide",
    "mathEqual",
    "mathMinus",
    "mathMultiply",
    "mathNotEqual",
    "mathPlus",
    "nonIsoscelesTrapezoid",
    "pieWedge",
    "plaqueTabs",
    "round1Rect",
    "round2DiagRect",
    "round2SameRect",
    "snip1Rect",
    "snip2DiagRect",
    "snip2SameRect",
    "snipRoundRect",
    "squareTabs",
    "straightConnector1"
  ],
  "stars": [
    "doubleWave",
    "ellipseRibbon",
    "ellipseRibbon2",
    "horizontalScroll",
    "irregularSeal1",
    "irregularSeal2",
    "leftRightRibbon",
    "ribbon",
    "ribbon2",
    "star10",
    "star12",
    "star16",
    "star24",
    "star32",
    "star4",
    "star5",
    "star6",
    "star7",
    "star8",
    "verticalScroll",
    "wave"
  ]
} as const;

/**
 * `+-` takes three operands in ECMA. Eight formulas in POI's file carry four,
 * every one of them ending in a spare `0`, and every one of them in the
 * circular-arrow family. Carried through verbatim: the evaluator decides what
 * to do with a fourth operand, not the transcoder.
 */
export const OVER_LONG_FORMULAS = [
  {
    "shape": "circularArrow",
    "guide": "xB",
    "fmla": "+- xH 0 dxB 0"
  },
  {
    "shape": "circularArrow",
    "guide": "yB",
    "fmla": "+- yH 0 dyB 0"
  },
  {
    "shape": "leftCircularArrow",
    "guide": "xB",
    "fmla": "+- xH 0 dxB 0"
  },
  {
    "shape": "leftCircularArrow",
    "guide": "yB",
    "fmla": "+- yH 0 dyB 0"
  },
  {
    "shape": "leftRightCircularArrow",
    "guide": "xB",
    "fmla": "+- xH 0 dxB 0"
  },
  {
    "shape": "leftRightCircularArrow",
    "guide": "yB",
    "fmla": "+- yH 0 dyB 0"
  },
  {
    "shape": "leftRightCircularArrow",
    "guide": "xJ",
    "fmla": "+- xI 0 dxJ 0"
  },
  {
    "shape": "leftRightCircularArrow",
    "guide": "yJ",
    "fmla": "+- yI 0 dyJ 0"
  }
] as const;

/**
 * Formulas written with a double space. Split on runs of whitespace, so the
 * operands are right; listed because a naive single-space split gives each of
 * these an empty operand and an arity one too high.
 */
export const COLLAPSED_WHITESPACE = [
  {
    "shape": "heptagon",
    "guide": "svc",
    "fmla": "*/ vc  vf 100000"
  },
  {
    "shape": "leftArrow",
    "guide": "x1",
    "fmla": "+- x2  0 dx1"
  },
  {
    "shape": "pentagon",
    "guide": "svc",
    "fmla": "*/ vc  vf 100000"
  },
  {
    "shape": "star5",
    "guide": "svc",
    "fmla": "*/ vc  vf 100000"
  },
  {
    "shape": "star7",
    "guide": "svc",
    "fmla": "*/ vc  vf 100000"
  },
  {
    "shape": "upArrow",
    "guide": "y1",
    "fmla": "+- y2  0 dy1"
  }
] as const;
